syntax = "proto3";

package ctk.ast.v1;

import "ast/v1/semantic_types.proto";

message TemplateTemplateParmDecl {
  NamedDeclInfo named = 1;
  TemplateParameterList template_parameters = 2;
  optional uint32 depth = 3;
  optional uint32 position = 4;
  optional bool is_parameter_pack = 5;
  TemplateArgument default_argument = 6;
  optional bool default_argument_was_inherited = 7;
  optional bool is_expanded_parameter_pack = 8;
  repeated TemplateParameterList expanded_template_parameters = 9;
}
