# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/analysis_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/analysis_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import traverse_request_pb2 as analysis_dot_v1_dot_traverse__request__pb2
from . import traverse_response_pb2 as analysis_dot_v1_dot_traverse__response__pb2
from . import cfg_request_pb2 as analysis_dot_v1_dot_cfg__request__pb2
from . import cfg_response_pb2 as analysis_dot_v1_dot_cfg__response__pb2
from . import call_graph_request_pb2 as analysis_dot_v1_dot_call__graph__request__pb2
from . import call_graph_response_pb2 as analysis_dot_v1_dot_call__graph__response__pb2
from . import script_request_pb2 as analysis_dot_v1_dot_script__request__pb2
from . import script_response_pb2 as analysis_dot_v1_dot_script__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"analysis/v1/analysis_service.proto\x12\x0f\x63tk.analysis.v1\x1a\"analysis/v1/traverse_request.proto\x1a#analysis/v1/traverse_response.proto\x1a\x1d\x61nalysis/v1/cfg_request.proto\x1a\x1e\x61nalysis/v1/cfg_response.proto\x1a$analysis/v1/call_graph_request.proto\x1a%analysis/v1/call_graph_response.proto\x1a analysis/v1/script_request.proto\x1a!analysis/v1/script_response.proto2\xc6\x02\n\x0f\x41nalysisService\x12L\n\tRunScript\x12\x1e.ctk.analysis.v1.ScriptRequest\x1a\x1f.ctk.analysis.v1.ScriptResponse\x12O\n\x08Traverse\x12 .ctk.analysis.v1.TraverseRequest\x1a!.ctk.analysis.v1.TraverseResponse\x12R\n\tCallGraph\x12!.ctk.analysis.v1.CallGraphRequest\x1a\".ctk.analysis.v1.CallGraphResponse\x12@\n\x03\x43\x66g\x12\x1b.ctk.analysis.v1.CfgRequest\x1a\x1c.ctk.analysis.v1.CfgResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.analysis_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYSISSERVICE']._serialized_start=338
  _globals['_ANALYSISSERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
