# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import call_graph_request_pb2 as analysis_dot_v1_dot_call__graph__request__pb2
from . import call_graph_response_pb2 as analysis_dot_v1_dot_call__graph__response__pb2
from . import cfg_request_pb2 as analysis_dot_v1_dot_cfg__request__pb2
from . import cfg_response_pb2 as analysis_dot_v1_dot_cfg__response__pb2
from . import script_request_pb2 as analysis_dot_v1_dot_script__request__pb2
from . import script_response_pb2 as analysis_dot_v1_dot_script__response__pb2
from . import traverse_request_pb2 as analysis_dot_v1_dot_traverse__request__pb2
from . import traverse_response_pb2 as analysis_dot_v1_dot_traverse__response__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analysis/v1/analysis_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunScript = channel.unary_unary(
                '/ctk.analysis.v1.AnalysisService/RunScript',
                request_serializer=analysis_dot_v1_dot_script__request__pb2.ScriptRequest.SerializeToString,
                response_deserializer=analysis_dot_v1_dot_script__response__pb2.ScriptResponse.FromString,
                _registered_method=True)
        self.Traverse = channel.unary_unary(
                '/ctk.analysis.v1.AnalysisService/Traverse',
                request_serializer=analysis_dot_v1_dot_traverse__request__pb2.TraverseRequest.SerializeToString,
                response_deserializer=analysis_dot_v1_dot_traverse__response__pb2.TraverseResponse.FromString,
                _registered_method=True)
        self.CallGraph = channel.unary_unary(
                '/ctk.analysis.v1.AnalysisService/CallGraph',
                request_serializer=analysis_dot_v1_dot_call__graph__request__pb2.CallGraphRequest.SerializeToString,
                response_deserializer=analysis_dot_v1_dot_call__graph__response__pb2.CallGraphResponse.FromString,
                _registered_method=True)
        self.Cfg = channel.unary_unary(
                '/ctk.analysis.v1.AnalysisService/Cfg',
                request_serializer=analysis_dot_v1_dot_cfg__request__pb2.CfgRequest.SerializeToString,
                response_deserializer=analysis_dot_v1_dot_cfg__response__pb2.CfgResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Traverse(self, request, context):
        """Owned semantic values from a standalone native AST visitor. On node/byte
        limits or cancellation, no partial response is returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunScript': grpc.unary_unary_rpc_method_handler(
                    servicer.RunScript,
                    request_deserializer=analysis_dot_v1_dot_script__request__pb2.ScriptRequest.FromString,
                    response_serializer=analysis_dot_v1_dot_script__response__pb2.ScriptResponse.SerializeToString,
            ),
            'Traverse': grpc.unary_unary_rpc_method_handler(
                    servicer.Traverse,
                    request_deserializer=analysis_dot_v1_dot_traverse__request__pb2.TraverseRequest.FromString,
                    response_serializer=analysis_dot_v1_dot_traverse__response__pb2.TraverseResponse.SerializeToString,
            ),
            'CallGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.CallGraph,
                    request_deserializer=analysis_dot_v1_dot_call__graph__request__pb2.CallGraphRequest.FromString,
                    response_serializer=analysis_dot_v1_dot_call__graph__response__pb2.CallGraphResponse.SerializeToString,
            ),
            'Cfg': grpc.unary_unary_rpc_method_handler(
                    servicer.Cfg,
                    request_deserializer=analysis_dot_v1_dot_cfg__request__pb2.CfgRequest.FromString,
                    response_serializer=analysis_dot_v1_dot_cfg__response__pb2.CfgResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ctk.analysis.v1.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ctk.analysis.v1.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.analysis.v1.AnalysisService/RunScript',
            analysis_dot_v1_dot_script__request__pb2.ScriptRequest.SerializeToString,
            analysis_dot_v1_dot_script__response__pb2.ScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Traverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.analysis.v1.AnalysisService/Traverse',
            analysis_dot_v1_dot_traverse__request__pb2.TraverseRequest.SerializeToString,
            analysis_dot_v1_dot_traverse__response__pb2.TraverseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.analysis.v1.AnalysisService/CallGraph',
            analysis_dot_v1_dot_call__graph__request__pb2.CallGraphRequest.SerializeToString,
            analysis_dot_v1_dot_call__graph__response__pb2.CallGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cfg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.analysis.v1.AnalysisService/Cfg',
            analysis_dot_v1_dot_cfg__request__pb2.CfgRequest.SerializeToString,
            analysis_dot_v1_dot_cfg__response__pb2.CfgResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
