# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/batch.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/batch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...match.v1 import resources_pb2 as match_dot_v1_dot_resources__pb2
from . import script_response_pb2 as analysis_dot_v1_dot_script__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalysis/v1/batch.proto\x12\x0f\x63tk.analysis.v1\x1a\x18match/v1/resources.proto\x1a!analysis/v1/script_response.proto\"\x94\x02\n\x11StartBatchRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12-\n\x06inputs\x18\x02 \x03(\x0b\x32\x1d.ctk.match.v1.InputDescriptor\x12\x13\n\x0b\x62ody_source\x18\x03 \x01(\t\x12\x16\n\x0egroup_variable\x18\x04 \x01(\t\x12\x0e\n\x04size\x18\x05 \x01(\rH\x00\x12\x0f\n\x05\x63ount\x18\x06 \x01(\rH\x00\x12\x11\n\x04jobs\x18\x07 \x01(\rH\x01\x88\x01\x01\x12\x19\n\x0cmemory_bytes\x18\x08 \x01(\x04H\x02\x88\x01\x01\x12\x19\n\x11\x63ontinue_on_error\x18\t \x01(\x08\x42\x0b\n\tpartitionB\x07\n\x05_jobsB\x0f\n\r_memory_bytes\"!\n\x0f\x42\x61tchRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"@\n\x13\x42\x61tchControlRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x19\n\x11\x65xpected_revision\x18\x02 \x01(\x04\":\n\x0b\x42\x61tchExport\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"\x9d\x02\n\nBatchGroup\x12\r\n\x05index\x18\x01 \x01(\r\x12-\n\x06inputs\x18\x02 \x03(\x0b\x32\x1d.ctk.match.v1.InputDescriptor\x12\x18\n\x10source_revisions\x18\x03 \x03(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x19\n\x11resource_scope_id\x18\x06 \x01(\t\x12\x1c\n\x14\x63leanup_acknowledged\x18\x07 \x01(\x08\x12/\n\x06result\x18\x08 \x01(\x0b\x32\x1f.ctk.analysis.v1.ScriptResponse\x12-\n\x07\x65xports\x18\t \x03(\x0b\x32\x1c.ctk.analysis.v1.BatchExport\"\xf3\x01\n\x08\x42\x61tchRun\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\x04\x12\r\n\x05state\x18\x03 \x01(\t\x12+\n\x06groups\x18\x04 \x03(\x0b\x32\x1b.ctk.analysis.v1.BatchGroup\x12\x18\n\x10results_complete\x18\x05 \x01(\x08\x12\x1c\n\x14peak_accounted_bytes\x18\x06 \x01(\x04\x12\x1b\n\x13peak_reserved_bytes\x18\x07 \x01(\x04\x12\x34\n\x08manifest\x18\x08 \x01(\x0b\x32\".ctk.analysis.v1.StartBatchRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.batch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTBATCHREQUEST']._serialized_start=106
  _globals['_STARTBATCHREQUEST']._serialized_end=382
  _globals['_BATCHRUNREQUEST']._serialized_start=384
  _globals['_BATCHRUNREQUEST']._serialized_end=417
  _globals['_BATCHCONTROLREQUEST']._serialized_start=419
  _globals['_BATCHCONTROLREQUEST']._serialized_end=483
  _globals['_BATCHEXPORT']._serialized_start=485
  _globals['_BATCHEXPORT']._serialized_end=543
  _globals['_BATCHGROUP']._serialized_start=546
  _globals['_BATCHGROUP']._serialized_end=831
  _globals['_BATCHRUN']._serialized_start=834
  _globals['_BATCHRUN']._serialized_end=1077
# @@protoc_insertion_point(module_scope)
