# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/call_graph_node.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/call_graph_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...ast.v1 import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2
try:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast_dot_v1_dot_semantic__pb2
except AttributeError:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast.v1.semantic_pb2
from ...ast.v1 import common_pb2 as ast_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!analysis/v1/call_graph_node.proto\x12\x0f\x63tk.analysis.v1\x1a\x1b\x61st/v1/semantic_types.proto\x1a\x13\x61st/v1/common.proto\"\xbb\x02\n\rCallGraphNode\x12\x12\n\nnode_index\x18\x01 \x01(\x04\x12\x17\n\x0fis_virtual_root\x18\x02 \x01(\x08\x12/\n\x08\x66unction\x18\x03 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12;\n\x15\x61nonymous_declaration\x18\x04 \x01(\x0b\x32\x1c.ctk.ast.v1.DeclarationValue\x12\x16\n\x0ehas_definition\x18\x05 \x01(\x08\x12\x18\n\x10\x64\x65\x63laration_kind\x18\x06 \x01(\t\x12\x18\n\x0bis_complete\x18\x07 \x01(\x08H\x00\x88\x01\x01\x12\x33\n\x0c\x61vailability\x18\x08 \x03(\x0b\x32\x1d.ctk.ast.v1.FieldAvailabilityB\x0e\n\x0c_is_completeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.call_graph_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLGRAPHNODE']._serialized_start=105
  _globals['_CALLGRAPHNODE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
