# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/call_graph_response.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/call_graph_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import call_graph_node_pb2 as analysis_dot_v1_dot_call__graph__node__pb2
from . import call_graph_edge_pb2 as analysis_dot_v1_dot_call__graph__edge__pb2
from ...ast.v1 import common_pb2 as ast_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%analysis/v1/call_graph_response.proto\x12\x0f\x63tk.analysis.v1\x1a!analysis/v1/call_graph_node.proto\x1a!analysis/v1/call_graph_edge.proto\x1a\x13\x61st/v1/common.proto\"\xe3\x01\n\x11\x43\x61llGraphResponse\x12\x11\n\troot_node\x18\x01 \x01(\x04\x12-\n\x05nodes\x18\x02 \x03(\x0b\x32\x1e.ctk.analysis.v1.CallGraphNode\x12-\n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32\x1e.ctk.analysis.v1.CallGraphEdge\x12\x18\n\x0bis_complete\x18\x04 \x01(\x08H\x00\x88\x01\x01\x12\x33\n\x0c\x61vailability\x18\x05 \x03(\x0b\x32\x1d.ctk.ast.v1.FieldAvailabilityB\x0e\n\x0c_is_completeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.call_graph_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLGRAPHRESPONSE']._serialized_start=150
  _globals['_CALLGRAPHRESPONSE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
