# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/call_graph_request.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/call_graph_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...match.v1 import match_service_pb2 as match_dot_v1_dot_match__service__pb2
from . import value_projection_pb2 as analysis_dot_v1_dot_value__projection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$analysis/v1/call_graph_request.proto\x12\x0f\x63tk.analysis.v1\x1a\x1cmatch/v1/match_service.proto\x1a\"analysis/v1/value_projection.proto\"\xe1\x02\n\x10\x43\x61llGraphRequest\x12+\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x1d.ctk.match.v1.FileMatchTarget\x12 \n\x13visit_implicit_code\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12*\n\x1dvisit_template_instantiations\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12\x16\n\tmax_nodes\x18\x04 \x01(\x04H\x02\x88\x01\x01\x12\x16\n\tmax_edges\x18\x05 \x01(\x04H\x03\x88\x01\x01\x12\x34\n\nprojection\x18\x06 \x01(\x0b\x32 .ctk.analysis.v1.ValueProjection\x12\x16\n\x0emain_file_only\x18\x07 \x01(\x08\x42\x16\n\x14_visit_implicit_codeB \n\x1e_visit_template_instantiationsB\x0c\n\n_max_nodesB\x0c\n\n_max_edgesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.call_graph_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLGRAPHREQUEST']._serialized_start=124
  _globals['_CALLGRAPHREQUEST']._serialized_end=477
# @@protoc_insertion_point(module_scope)
