# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_block.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_block.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...ast.v1 import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2
try:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast_dot_v1_dot_semantic__pb2
except AttributeError:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast.v1.semantic_pb2
from ...ast.v1 import common_pb2 as ast_dot_v1_dot_common__pb2
from . import cfg_element_pb2 as analysis_dot_v1_dot_cfg__element__pb2
from . import cfg_edge_pb2 as analysis_dot_v1_dot_cfg__edge__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61nalysis/v1/cfg_block.proto\x12\x0f\x63tk.analysis.v1\x1a\x1b\x61st/v1/semantic_types.proto\x1a\x13\x61st/v1/common.proto\x1a\x1d\x61nalysis/v1/cfg_element.proto\x1a\x1a\x61nalysis/v1/cfg_edge.proto\"\xfa\x05\n\x08\x43\x66gBlock\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\x04\x12-\n\x08\x65lements\x18\x02 \x03(\x0b\x32\x1b.ctk.analysis.v1.CfgElement\x12.\n\x0cpredecessors\x18\x03 \x03(\x0b\x32\x18.ctk.analysis.v1.CfgEdge\x12,\n\nsuccessors\x18\x04 \x03(\x0b\x32\x18.ctk.analysis.v1.CfgEdge\x12)\n\x05label\x18\x05 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12/\n\x0bloop_target\x18\x06 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x46\n\x0fterminator_kind\x18\x07 \x01(\x0e\x32(.ctk.analysis.v1.CfgBlock.TerminatorKindH\x00\x88\x01\x01\x12.\n\nterminator\x18\x08 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x38\n\x14terminator_condition\x18\t \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x33\n\x0elast_condition\x18\n \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x1d\n\x15has_no_return_element\x18\x0b \x01(\x08\x12\x18\n\x0bis_complete\x18\x0c \x01(\x08H\x01\x88\x01\x01\x12\x33\n\x0c\x61vailability\x18\r \x03(\x0b\x32\x1d.ctk.ast.v1.FieldAvailability\"w\n\x0eTerminatorKind\x12\x1a\n\x16TERMINATOR_UNSPECIFIED\x10\x00\x12\x14\n\x10STATEMENT_BRANCH\x10\x01\x12\x1a\n\x16TEMPORARY_DTORS_BRANCH\x10\x02\x12\x17\n\x13VIRTUAL_BASE_BRANCH\x10\x03\x42\x12\n\x10_terminator_kindB\x0e\n\x0c_is_completeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_block_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGBLOCK']._serialized_start=158
  _globals['_CFGBLOCK']._serialized_end=920
  _globals['_CFGBLOCK_TERMINATORKIND']._serialized_start=765
  _globals['_CFGBLOCK_TERMINATORKIND']._serialized_end=884
# @@protoc_insertion_point(module_scope)
