# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_edge.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_edge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61nalysis/v1/cfg_edge.proto\x12\x0f\x63tk.analysis.v1\"\x99\x01\n\x07\x43\x66gEdge\x12\x1c\n\x0freachable_block\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\'\n\x1apossibly_unreachable_block\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x14\n\x0cis_reachable\x18\x03 \x01(\x08\x42\x12\n\x10_reachable_blockB\x1d\n\x1b_possibly_unreachable_blockb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_edge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGEDGE']._serialized_start=48
  _globals['_CFGEDGE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
