# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_options.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61nalysis/v1/cfg_options.proto\x12\x0f\x63tk.analysis.v1\"\x8a\x05\n\nCfgOptions\x12(\n\x1bprune_trivially_false_edges\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x0c\x61\x64\x64_eh_edges\x18\x02 \x01(\x08\x12\x18\n\x10\x61\x64\x64_initializers\x18\x03 \x01(\x08\x12\x1a\n\x12\x61\x64\x64_implicit_dtors\x18\x04 \x01(\x08\x12\x1b\n\x13\x61\x64\x64_temporary_dtors\x18\x05 \x01(\x08\x12\x14\n\x0c\x61\x64\x64_lifetime\x18\x06 \x01(\x08\x12\x12\n\nadd_scopes\x18\x07 \x01(\x08\x12\x15\n\radd_loop_exit\x18\x08 \x01(\x08\x12 \n\x18\x61\x64\x64_static_init_branches\x18\t \x01(\x08\x12\x1d\n\x15\x61\x64\x64_cxx_new_allocator\x18\n \x01(\x08\x12*\n\"add_cxx_default_init_expr_in_ctors\x18\x0b \x01(\x08\x12/\n\'add_cxx_default_init_expr_in_aggregates\x18\x0c \x01(\x08\x12!\n\x19\x61\x64\x64_rich_cxx_constructors\x18\r \x01(\x08\x12$\n\x1cmark_elided_cxx_constructors\x18\x0e \x01(\x08\x12!\n\x19\x61\x64\x64_virtual_base_branches\x18\x0f \x01(\x08\x12(\n omit_implicit_value_initializers\x18\x10 \x01(\x08\x12\x35\n-assume_reachable_default_in_switch_statements\x18\x11 \x01(\x08\x12\x1d\n\x15\x61lways_add_statements\x18\x12 \x01(\x08\x42\x1e\n\x1c_prune_trivially_false_edgesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGOPTIONS']._serialized_start=51
  _globals['_CFGOPTIONS']._serialized_end=701
# @@protoc_insertion_point(module_scope)
