# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_statement.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_statement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...ast.v1 import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2
try:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast_dot_v1_dot_semantic__pb2
except AttributeError:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast.v1.semantic_pb2
from . import cfg_construction_context_pb2 as analysis_dot_v1_dot_cfg__construction__context__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61nalysis/v1/cfg_statement.proto\x12\x0f\x63tk.analysis.v1\x1a\x1b\x61st/v1/semantic_types.proto\x1a*analysis/v1/cfg_construction_context.proto\"\x84\x01\n\x0c\x43\x66gStatement\x12-\n\tstatement\x18\x01 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x45\n\x14\x63onstruction_context\x18\x02 \x01(\x0b\x32\'.ctk.analysis.v1.CfgConstructionContextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_statement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGSTATEMENT']._serialized_start=126
  _globals['_CFGSTATEMENT']._serialized_end=258
# @@protoc_insertion_point(module_scope)
