# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_response.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import cfg_graph_pb2 as analysis_dot_v1_dot_cfg__graph__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61nalysis/v1/cfg_response.proto\x12\x0f\x63tk.analysis.v1\x1a\x1b\x61nalysis/v1/cfg_graph.proto\"8\n\x0b\x43\x66gResponse\x12)\n\x06graphs\x18\x01 \x03(\x0b\x32\x19.ctk.analysis.v1.CfgGraphb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGRESPONSE']._serialized_start=80
  _globals['_CFGRESPONSE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
