# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_request.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...match.v1 import match_service_pb2 as match_dot_v1_dot_match__service__pb2
from . import cfg_options_pb2 as analysis_dot_v1_dot_cfg__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61nalysis/v1/cfg_request.proto\x12\x0f\x63tk.analysis.v1\x1a\x1cmatch/v1/match_service.proto\x1a\x1d\x61nalysis/v1/cfg_options.proto\"\xfb\x01\n\nCfgRequest\x12+\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x1d.ctk.match.v1.FileMatchTarget\x12\x10\n\x08\x66unction\x18\x02 \x01(\t\x12,\n\x07options\x18\x03 \x01(\x0b\x32\x1b.ctk.analysis.v1.CfgOptions\x12\x1a\n\rmax_functions\x18\x04 \x01(\x04H\x00\x88\x01\x01\x12\x17\n\nmax_blocks\x18\x05 \x01(\x04H\x01\x88\x01\x01\x12\x19\n\x0cmax_elements\x18\x06 \x01(\x04H\x02\x88\x01\x01\x42\x10\n\x0e_max_functionsB\r\n\x0b_max_blocksB\x0f\n\r_max_elementsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGREQUEST']._serialized_start=112
  _globals['_CFGREQUEST']._serialized_end=363
# @@protoc_insertion_point(module_scope)
