# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_element.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_element.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...ast.v1 import common_pb2 as ast_dot_v1_dot_common__pb2
from . import cfg_statement_pb2 as analysis_dot_v1_dot_cfg__statement__pb2
from . import cfg_initializer_pb2 as analysis_dot_v1_dot_cfg__initializer__pb2
from . import cfg_scope_event_pb2 as analysis_dot_v1_dot_cfg__scope__event__pb2
from . import cfg_new_allocator_pb2 as analysis_dot_v1_dot_cfg__new__allocator__pb2
from . import cfg_loop_exit_pb2 as analysis_dot_v1_dot_cfg__loop__exit__pb2
from . import cfg_destructor_pb2 as analysis_dot_v1_dot_cfg__destructor__pb2
from . import cfg_cleanup_pb2 as analysis_dot_v1_dot_cfg__cleanup__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61nalysis/v1/cfg_element.proto\x12\x0f\x63tk.analysis.v1\x1a\x13\x61st/v1/common.proto\x1a\x1f\x61nalysis/v1/cfg_statement.proto\x1a!analysis/v1/cfg_initializer.proto\x1a!analysis/v1/cfg_scope_event.proto\x1a#analysis/v1/cfg_new_allocator.proto\x1a\x1f\x61nalysis/v1/cfg_loop_exit.proto\x1a analysis/v1/cfg_destructor.proto\x1a\x1d\x61nalysis/v1/cfg_cleanup.proto\"\xc7\x06\n\nCfgElement\x12.\n\x04kind\x18\x01 \x01(\x0e\x32 .ctk.analysis.v1.CfgElement.Kind\x12\x32\n\tstatement\x18\x02 \x01(\x0b\x32\x1d.ctk.analysis.v1.CfgStatementH\x00\x12\x36\n\x0binitializer\x18\x03 \x01(\x0b\x32\x1f.ctk.analysis.v1.CfgInitializerH\x00\x12/\n\x05scope\x18\x04 \x01(\x0b\x32\x1e.ctk.analysis.v1.CfgScopeEventH\x00\x12\x35\n\tallocator\x18\x05 \x01(\x0b\x32 .ctk.analysis.v1.CfgNewAllocatorH\x00\x12\x31\n\tloop_exit\x18\x06 \x01(\x0b\x32\x1c.ctk.analysis.v1.CfgLoopExitH\x00\x12\x34\n\ndestructor\x18\x07 \x01(\x0b\x32\x1e.ctk.analysis.v1.CfgDestructorH\x00\x12.\n\x07\x63leanup\x18\x08 \x01(\x0b\x32\x1b.ctk.analysis.v1.CfgCleanupH\x00\x12\x18\n\x0bis_complete\x18\t \x01(\x08H\x01\x88\x01\x01\x12\x33\n\x0c\x61vailability\x18\n \x03(\x0b\x32\x1d.ctk.ast.v1.FieldAvailability\"\xb3\x02\n\x04Kind\x12\x14\n\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n\x0bINITIALIZER\x10\x01\x12\x0f\n\x0bSCOPE_BEGIN\x10\x02\x12\r\n\tSCOPE_END\x10\x03\x12\x11\n\rNEW_ALLOCATOR\x10\x04\x12\x11\n\rLIFETIME_ENDS\x10\x05\x12\r\n\tLOOP_EXIT\x10\x06\x12\r\n\tSTATEMENT\x10\x07\x12\x0f\n\x0b\x43ONSTRUCTOR\x10\x08\x12\x19\n\x15\x43XX_RECORD_TYPED_CALL\x10\t\x12\x19\n\x15\x41UTOMATIC_OBJECT_DTOR\x10\n\x12\x0f\n\x0b\x44\x45LETE_DTOR\x10\x0b\x12\r\n\tBASE_DTOR\x10\x0c\x12\x0f\n\x0bMEMBER_DTOR\x10\r\x12\x12\n\x0eTEMPORARY_DTOR\x10\x0e\x12\x14\n\x10\x43LEANUP_FUNCTION\x10\x0f\x42\x07\n\x05valueB\x0e\n\x0c_is_completeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_element_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGELEMENT']._serialized_start=310
  _globals['_CFGELEMENT']._serialized_end=1149
  _globals['_CFGELEMENT_KIND']._serialized_start=817
  _globals['_CFGELEMENT_KIND']._serialized_end=1124
# @@protoc_insertion_point(module_scope)
