# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_destructor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_destructor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...ast.v1 import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2
try:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast_dot_v1_dot_semantic__pb2
except AttributeError:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast.v1.semantic_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n analysis/v1/cfg_destructor.proto\x12\x0f\x63tk.analysis.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xbf\x02\n\rCfgDestructor\x12\x31\n\ndestructor\x18\x01 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12\x14\n\x0cis_no_return\x18\x02 \x01(\x08\x12/\n\x08variable\x18\x03 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12-\n\x06record\x18\x04 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12,\n\x05\x66ield\x18\x05 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12*\n\x04\x62\x61se\x18\x06 \x01(\x0b\x32\x1c.ctk.ast.v1.CXXBaseSpecifier\x12+\n\x07trigger\x18\x07 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_destructor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGDESTRUCTOR']._serialized_start=83
  _globals['_CFGDESTRUCTOR']._serialized_end=402
# @@protoc_insertion_point(module_scope)
