# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/cfg_graph.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/cfg_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...ast.v1 import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2
try:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast_dot_v1_dot_semantic__pb2
except AttributeError:
  ast_dot_v1_dot_semantic__pb2 = ast_dot_v1_dot_semantic__types__pb2.ast.v1.semantic_pb2
from ...ast.v1 import common_pb2 as ast_dot_v1_dot_common__pb2
from . import cfg_block_pb2 as analysis_dot_v1_dot_cfg__block__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61nalysis/v1/cfg_graph.proto\x12\x0f\x63tk.analysis.v1\x1a\x1b\x61st/v1/semantic_types.proto\x1a\x13\x61st/v1/common.proto\x1a\x1b\x61nalysis/v1/cfg_block.proto\"\x81\x02\n\x08\x43\x66gGraph\x12/\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12\x13\n\x0b\x65ntry_block\x18\x02 \x01(\x04\x12\x12\n\nexit_block\x18\x03 \x01(\x04\x12)\n\x06\x62locks\x18\x04 \x03(\x0b\x32\x19.ctk.analysis.v1.CfgBlock\x12\x11\n\tis_linear\x18\x05 \x01(\x08\x12\x18\n\x0bis_complete\x18\x06 \x01(\x08H\x00\x88\x01\x01\x12\x33\n\x0c\x61vailability\x18\x07 \x03(\x0b\x32\x1d.ctk.ast.v1.FieldAvailabilityB\x0e\n\x0c_is_completeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.cfg_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CFGGRAPH']._serialized_start=128
  _globals['_CFGGRAPH']._serialized_end=385
# @@protoc_insertion_point(module_scope)
