# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/script_match_rows.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/script_match_rows.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...match.v1 import match_result_pb2 as match_dot_v1_dot_match__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#analysis/v1/script_match_rows.proto\x12\x0f\x63tk.analysis.v1\x1a\x1bmatch/v1/match_result.proto\":\n\x0fScriptMatchRows\x12\'\n\x04rows\x18\x01 \x03(\x0b\x32\x19.ctk.match.v1.MatchResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.script_match_rows_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIPTMATCHROWS']._serialized_start=85
  _globals['_SCRIPTMATCHROWS']._serialized_end=143
# @@protoc_insertion_point(module_scope)
