# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/script_request.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/script_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...match.v1 import match_service_pb2 as match_dot_v1_dot_match__service__pb2
from . import script_compilation_profile_pb2 as analysis_dot_v1_dot_script__compilation__profile__pb2
from . import script_value_pb2 as analysis_dot_v1_dot_script__value__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n analysis/v1/script_request.proto\x12\x0f\x63tk.analysis.v1\x1a\x1cmatch/v1/match_service.proto\x1a,analysis/v1/script_compilation_profile.proto\x1a\x1e\x61nalysis/v1/script_value.proto\"\xff\x02\n\rScriptRequest\x12+\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x1d.ctk.match.v1.FileMatchTarget\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x16\n\tmax_steps\x18\x03 \x01(\rH\x00\x88\x01\x01\x12:\n\x07profile\x18\x04 \x01(\x0b\x32).ctk.analysis.v1.ScriptCompilationProfile\x12\x19\n\x11resource_scope_id\x18\x05 \x01(\t\x12I\n\x0einitial_values\x18\x06 \x03(\x0b\x32\x31.ctk.analysis.v1.ScriptRequest.InitialValuesEntry\x12\x15\n\rcollect_final\x18\x07 \x01(\x08\x1aR\n\x12InitialValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.ctk.analysis.v1.ScriptValue:\x02\x38\x01\x42\x0c\n\n_max_stepsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.script_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIPTREQUEST_INITIALVALUESENTRY']._loaded_options = None
  _globals['_SCRIPTREQUEST_INITIALVALUESENTRY']._serialized_options = b'8\001'
  _globals['_SCRIPTREQUEST']._serialized_start=162
  _globals['_SCRIPTREQUEST']._serialized_end=545
  _globals['_SCRIPTREQUEST_INITIALVALUESENTRY']._serialized_start=449
  _globals['_SCRIPTREQUEST_INITIALVALUESENTRY']._serialized_end=531
# @@protoc_insertion_point(module_scope)
