# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/script_value.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/script_value.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import script_scalar_pb2 as analysis_dot_v1_dot_script__scalar__pb2
from . import script_match_rows_pb2 as analysis_dot_v1_dot_script__match__rows__pb2
from . import traverse_response_pb2 as analysis_dot_v1_dot_traverse__response__pb2
from . import cfg_response_pb2 as analysis_dot_v1_dot_cfg__response__pb2
from . import call_graph_response_pb2 as analysis_dot_v1_dot_call__graph__response__pb2
from . import script_tree_pb2 as analysis_dot_v1_dot_script__tree__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61nalysis/v1/script_value.proto\x12\x0f\x63tk.analysis.v1\x1a\x1f\x61nalysis/v1/script_scalar.proto\x1a#analysis/v1/script_match_rows.proto\x1a#analysis/v1/traverse_response.proto\x1a\x1e\x61nalysis/v1/cfg_response.proto\x1a%analysis/v1/call_graph_response.proto\x1a\x1d\x61nalysis/v1/script_tree.proto\"\xc8\x02\n\x0bScriptValue\x12/\n\x06scalar\x18\x01 \x01(\x0b\x32\x1d.ctk.analysis.v1.ScriptScalarH\x00\x12\x33\n\x07matches\x18\x02 \x01(\x0b\x32 .ctk.analysis.v1.ScriptMatchRowsH\x00\x12\x36\n\ttraversal\x18\x03 \x01(\x0b\x32!.ctk.analysis.v1.TraverseResponseH\x00\x12+\n\x03\x63\x66g\x18\x04 \x01(\x0b\x32\x1c.ctk.analysis.v1.CfgResponseH\x00\x12\x38\n\ncall_graph\x18\x05 \x01(\x0b\x32\".ctk.analysis.v1.CallGraphResponseH\x00\x12+\n\x04tree\x18\x06 \x01(\x0b\x32\x1b.ctk.analysis.v1.ScriptTreeH\x00\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.script_value_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIPTVALUE']._serialized_start=261
  _globals['_SCRIPTVALUE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
