# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/script_emission.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/script_emission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import script_value_pb2 as analysis_dot_v1_dot_script__value__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!analysis/v1/script_emission.proto\x12\x0f\x63tk.analysis.v1\x1a\x1e\x61nalysis/v1/script_value.proto\"K\n\x0eScriptEmission\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.ctk.analysis.v1.ScriptValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.script_emission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIPTEMISSION']._serialized_start=86
  _globals['_SCRIPTEMISSION']._serialized_end=161
# @@protoc_insertion_point(module_scope)
