# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis/v1/traversal_node.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analysis/v1/traversal_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...match.v1 import match_result_pb2 as match_dot_v1_dot_match__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n analysis/v1/traversal_node.proto\x12\x0f\x63tk.analysis.v1\x1a\x1bmatch/v1/match_result.proto\"u\n\rTraversalNode\x12\x19\n\x0cparent_index\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\x12)\n\x05value\x18\x03 \x01(\x0b\x32\x1a.ctk.match.v1.MatchBindingB\x0f\n\r_parent_indexb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis.v1.traversal_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAVERSALNODE']._serialized_start=82
  _globals['_TRAVERSALNODE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
