# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/attributed_type.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/attributed_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61st/v1/attributed_type.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xc9\x02\n\x0e\x41ttributedType\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.TypeInfo\x12+\n\rmodified_type\x18\x02 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12-\n\x0f\x65quivalent_type\x18\x03 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12;\n\x0e\x61ttribute_kind\x18\x04 \x01(\x0e\x32\x1e.ctk.ast.v1.AttributedTypeKindH\x00\x88\x01\x01\x12-\n\tattribute\x18\x05 \x01(\x0b\x32\x1a.ctk.ast.v1.AttributeValue\x12 \n\x13\x61ttribute_kind_name\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\x11\n\x0f_attribute_kindB\x16\n\x14_attribute_kind_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.attributed_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTRIBUTEDTYPE']._serialized_start=74
  _globals['_ATTRIBUTEDTYPE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
