# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/coawait_expr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/coawait_expr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61st/v1/coawait_expr.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\x99\x02\n\x0b\x43oawaitExpr\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.ExprInfo\x12,\n\x07operand\x18\x02 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12/\n\nready_call\x18\x03 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x31\n\x0csuspend_call\x18\x04 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x30\n\x0bresume_call\x18\x05 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x15\n\x08is_ready\x18\x06 \x01(\x08H\x00\x88\x01\x01\x42\x0b\n\t_is_readyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.coawait_expr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COAWAITEXPR']._serialized_start=71
  _globals['_COAWAITEXPR']._serialized_end=352
# @@protoc_insertion_point(module_scope)
