# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/coroutine_body_stmt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/coroutine_body_stmt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ast/v1/coroutine_body_stmt.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xdd\x03\n\x11\x43oroutineBodyStmt\x12(\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x39\n\x13promise_declaration\x18\x03 \x01(\x0b\x32\x1c.ctk.ast.v1.DeclarationValue\x12\x31\n\x0creturn_value\x18\x04 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x35\n\x11\x65xception_handler\x18\x05 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x37\n\x13\x66\x61llthrough_handler\x18\x06 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x33\n\x0fparameter_moves\x18\x07 \x03(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12;\n\x16\x61llocation_expressions\x18\x08 \x03(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12=\n\x18\x64\x65\x61llocation_expressions\x18\t \x03(\x0b\x32\x1b.ctk.ast.v1.ExpressionValueJ\x04\x08\x01\x10\x02R\tstatementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.coroutine_body_stmt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COROUTINEBODYSTMT']._serialized_start=78
  _globals['_COROUTINEBODYSTMT']._serialized_end=555
# @@protoc_insertion_point(module_scope)
