# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/cxx_pseudo_destructor_expr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/cxx_pseudo_destructor_expr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ast/v1/cxx_pseudo_destructor_expr.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xee\x01\n\x17\x43XXPseudoDestructorExpr\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.ExprInfo\x12)\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x32\n\tqualifier\x18\x03 \x01(\x0b\x32\x1f.ctk.ast.v1.NestedNameSpecifier\x12,\n\x0e\x64\x65stroyed_type\x18\x04 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12\x15\n\x08is_arrow\x18\x05 \x01(\x08H\x00\x88\x01\x01\x42\x0b\n\t_is_arrowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.cxx_pseudo_destructor_expr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CXXPSEUDODESTRUCTOREXPR']._serialized_start=85
  _globals['_CXXPSEUDODESTRUCTOREXPR']._serialized_end=323
# @@protoc_insertion_point(module_scope)
