# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/cxx_conversion_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/cxx_conversion_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ast/v1/cxx_conversion_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xfa\x01\n\x11\x43XXConversionDecl\x12-\n\x06method\x18\x01 \x01(\x0b\x32\x1d.ctk.ast.v1.CXXMethodDeclInfo\x12\x18\n\x0bis_explicit\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12(\n\x1bis_explicit_specifier_value\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12\x42\n\x1d\x65xplicit_specifier_expression\x18\x04 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValueB\x0e\n\x0c_is_explicitB\x1e\n\x1c_is_explicit_specifier_valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.cxx_conversion_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CXXCONVERSIONDECL']._serialized_start=78
  _globals['_CXXCONVERSIONDECL']._serialized_end=328
# @@protoc_insertion_point(module_scope)
