# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/cxx_deduction_guide_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/cxx_deduction_guide_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ast/v1/cxx_deduction_guide_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xc1\x03\n\x15\x43XXDeductionGuideDecl\x12.\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x1c.ctk.ast.v1.FunctionDeclInfo\x12\x37\n\x10\x64\x65\x64uced_template\x18\x02 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12M\n\x18\x64\x65\x64uction_candidate_kind\x18\x03 \x01(\x0e\x32&.ctk.ast.v1.DeclDeductionCandidateKindH\x00\x88\x01\x01\x12@\n\x19\x63orresponding_constructor\x18\x04 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12=\n\x16source_deduction_guide\x18\x05 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12\x42\n\x0bsource_kind\x18\x06 \x01(\x0e\x32(.ctk.ast.v1.DeclSourceDeductionGuideKindH\x01\x88\x01\x01\x42\x1b\n\x19_deduction_candidate_kindB\x0e\n\x0c_source_kindb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.cxx_deduction_guide_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CXXDEDUCTIONGUIDEDECL']._serialized_start=83
  _globals['_CXXDEDUCTIONGUIDEDECL']._serialized_end=532
# @@protoc_insertion_point(module_scope)
