# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/cxx_new_expr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/cxx_new_expr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61st/v1/cxx_new_expr.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\x8e\x04\n\nCXXNewExpr\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.ExprInfo\x12\x33\n\x0coperator_new\x18\x02 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12\x36\n\x0foperator_delete\x18\x03 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12,\n\x0e\x61llocated_type\x18\x04 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12/\n\narray_size\x18\x05 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x30\n\x0binitializer\x18\x06 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x15\n\x08is_array\x18\x07 \x01(\x08H\x00\x88\x01\x01\x12\x1a\n\ris_global_new\x18\x08 \x01(\x08H\x01\x88\x01\x01\x12\x17\n\nis_nothrow\x18\t \x01(\x08H\x02\x88\x01\x01\x12\x19\n\x0cis_placement\x18\n \x01(\x08H\x03\x88\x01\x01\x12\x38\n\x13placement_arguments\x18\x0b \x03(\x0b\x32\x1b.ctk.ast.v1.ExpressionValueB\x0b\n\t_is_arrayB\x10\n\x0e_is_global_newB\r\n\x0b_is_nothrowB\x0f\n\r_is_placementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.cxx_new_expr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CXXNEWEXPR']._serialized_start=71
  _globals['_CXXNEWEXPR']._serialized_end=597
# @@protoc_insertion_point(module_scope)
