# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/cxx_operator_call_expr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/cxx_operator_call_expr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import operators_pb2 as ast_dot_v1_dot_operators__pb2  # noqa: E402, F401
from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ast/v1/cxx_operator_call_expr.proto\x12\nctk.ast.v1\x1a\x16\x61st/v1/operators.proto\x1a\x1b\x61st/v1/semantic_types.proto\"\x8f\x01\n\x13\x43XXOperatorCallExpr\x12&\n\x04\x63\x61ll\x18\x01 \x01(\x0b\x32\x18.ctk.ast.v1.CallExprInfo\x12>\n\roperator_kind\x18\x02 \x01(\x0e\x32\".ctk.ast.v1.OverloadedOperatorKindH\x00\x88\x01\x01\x42\x10\n\x0e_operator_kindb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.cxx_operator_call_expr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CXXOPERATORCALLEXPR']._serialized_start=105
  _globals['_CXXOPERATORCALLEXPR']._serialized_end=248
# @@protoc_insertion_point(module_scope)
