# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/decl_ref_expr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/decl_ref_expr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61st/v1/decl_ref_expr.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\x80\x03\n\x0b\x44\x65\x63lRefExpr\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.ExprInfo\x12\x32\n\x0b\x64\x65\x63laration\x18\x02 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12)\n\x04name\x18\x03 \x01(\x0b\x32\x1b.ctk.ast.v1.DeclarationName\x12\x32\n\tqualifier\x18\x04 \x01(\x0b\x32\x1f.ctk.ast.v1.NestedNameSpecifier\x12\x1b\n\x0eis_non_odr_use\x18\x05 \x01(\x08H\x00\x88\x01\x01\x12,\n\x1fhas_explicit_template_arguments\x18\x06 \x01(\x08H\x01\x88\x01\x01\x12\x38\n\x12template_arguments\x18\x07 \x03(\x0b\x32\x1c.ctk.ast.v1.TemplateArgumentB\x11\n\x0f_is_non_odr_useB\"\n _has_explicit_template_argumentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.decl_ref_expr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECLREFEXPR']._serialized_start=72
  _globals['_DECLREFEXPR']._serialized_end=456
# @@protoc_insertion_point(module_scope)
