# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/dependent_sized_array_type.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/dependent_sized_array_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as ast_dot_v1_dot_common__pb2  # noqa: E402, F401
from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ast/v1/dependent_sized_array_type.proto\x12\nctk.ast.v1\x1a\x13\x61st/v1/common.proto\x1a\x1b\x61st/v1/semantic_types.proto\"\x9e\x02\n\x17\x44\x65pendentSizedArrayType\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.TypeInfo\x12*\n\x0c\x65lement_type\x18\x02 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12\x34\n\x0fsize_expression\x18\x03 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x39\n\rsize_modifier\x18\x04 \x01(\x0e\x32\x1d.ctk.ast.v1.ArraySizeModifierH\x00\x88\x01\x01\x12\x30\n\x10index_qualifiers\x18\x05 \x01(\x0b\x32\x16.ctk.ast.v1.QualifiersB\x10\n\x0e_size_modifierb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.dependent_sized_array_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPENDENTSIZEDARRAYTYPE']._serialized_start=106
  _globals['_DEPENDENTSIZEDARRAYTYPE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
