# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/enum_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/enum_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61st/v1/enum_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xd4\x01\n\x08\x45numDecl\x12$\n\x03tag\x18\x01 \x01(\x0b\x32\x17.ctk.ast.v1.TagDeclInfo\x12*\n\x0cinteger_type\x18\x02 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12,\n\x0epromotion_type\x18\x03 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12\x16\n\tis_scoped\x18\x04 \x01(\x08H\x00\x88\x01\x01\x12\x15\n\x08is_fixed\x18\x05 \x01(\x08H\x01\x88\x01\x01\x42\x0c\n\n_is_scopedB\x0b\n\t_is_fixedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.enum_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENUMDECL']._serialized_start=68
  _globals['_ENUMDECL']._serialized_end=280
# @@protoc_insertion_point(module_scope)
