# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/for_stmt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/for_stmt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61st/v1/for_stmt.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\x92\x02\n\x07\x46orStmt\x12\x32\n\x0einit_statement\x18\x02 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValue\x12\x38\n\x12\x63ondition_variable\x18\x03 \x01(\x0b\x32\x1c.ctk.ast.v1.DeclarationValue\x12.\n\tcondition\x18\x04 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12.\n\tincrement\x18\x05 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12(\n\x04\x62ody\x18\x06 \x01(\x0b\x32\x1a.ctk.ast.v1.StatementValueJ\x04\x08\x01\x10\x02R\tstatementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.for_stmt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORSTMT']._serialized_start=67
  _globals['_FORSTMT']._serialized_end=341
# @@protoc_insertion_point(module_scope)
