# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/function_proto_type.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/function_proto_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ast/v1/function_proto_type.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xa4\x02\n\x11\x46unctionProtoType\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.TypeInfo\x12)\n\x0breturn_type\x18\x02 \x01(\x0b\x32\x14.ctk.ast.v1.QualType\x12-\n\x0fparameter_types\x18\x03 \x03(\x0b\x32\x14.ctk.ast.v1.QualType\x12\x18\n\x0bis_variadic\x18\x04 \x01(\x08H\x00\x88\x01\x01\x12-\n\x08\x65xt_info\x18\x05 \x01(\x0b\x32\x1b.ctk.ast.v1.FunctionExtInfo\x12\x38\n\x0eprototype_info\x18\x06 \x01(\x0b\x32 .ctk.ast.v1.FunctionProtoExtInfoB\x0e\n\x0c_is_variadicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.function_proto_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUNCTIONPROTOTYPE']._serialized_start=78
  _globals['_FUNCTIONPROTOTYPE']._serialized_end=370
# @@protoc_insertion_point(module_scope)
