# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/function_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/function_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61st/v1/function_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xbf\x03\n\x0c\x46unctionDecl\x12.\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x1c.ctk.ast.v1.FunctionDeclInfo\x12\x17\n\nis_deleted\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12\x19\n\x0cis_defaulted\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12$\n\x17is_explicitly_defaulted\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\x1c\n\x0fis_pure_virtual\x18\x05 \x01(\x08H\x03\x88\x01\x01\x12\x17\n\nis_trivial\x18\x07 \x01(\x08H\x04\x88\x01\x01\x12 \n\x13is_trivial_for_call\x18\x08 \x01(\x08H\x05\x88\x01\x01\x12 \n\x13is_inline_specified\x18\t \x01(\x08H\x06\x88\x01\x01\x42\r\n\x0b_is_deletedB\x0f\n\r_is_defaultedB\x1a\n\x18_is_explicitly_defaultedB\x12\n\x10_is_pure_virtualB\r\n\x0b_is_trivialB\x16\n\x14_is_trivial_for_callB\x16\n\x14_is_inline_specifiedJ\x04\x08\x06\x10\x07R\x15is_virtual_as_writtenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.function_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUNCTIONDECL']._serialized_start=72
  _globals['_FUNCTIONDECL']._serialized_end=519
# @@protoc_insertion_point(module_scope)
