# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/lambda_expr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/lambda_expr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61st/v1/lambda_expr.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xe2\x02\n\nLambdaExpr\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.ExprInfo\x12\x34\n\rclosure_class\x18\x02 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12+\n\x08\x63\x61ptures\x18\x03 \x03(\x0b\x32\x19.ctk.ast.v1.LambdaCapture\x12\x39\n\x14\x63\x61pture_initializers\x18\x04 \x03(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12\x34\n\rcall_operator\x18\x05 \x01(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12\x1e\n\x11is_generic_lambda\x18\x06 \x01(\x08H\x00\x88\x01\x01\x12\x17\n\nis_mutable\x18\x07 \x01(\x08H\x01\x88\x01\x01\x42\x14\n\x12_is_generic_lambdaB\r\n\x0b_is_mutableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.lambda_expr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAMBDAEXPR']._serialized_start=70
  _globals['_LAMBDAEXPR']._serialized_end=424
# @@protoc_insertion_point(module_scope)
