# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/ms_asm_stmt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/ms_asm_stmt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61st/v1/ms_asm_stmt.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xbb\x02\n\tMSAsmStmt\x12\x17\n\nasm_string\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\'\n\x07outputs\x18\x03 \x03(\x0b\x32\x16.ctk.ast.v1.AsmOperand\x12&\n\x06inputs\x18\x04 \x03(\x0b\x32\x16.ctk.ast.v1.AsmOperand\x12\x10\n\x08\x63lobbers\x18\x05 \x03(\t\x12\x16\n\tis_simple\x18\x06 \x01(\x08H\x01\x88\x01\x01\x12\x18\n\x0bis_volatile\x18\x07 \x01(\x08H\x02\x88\x01\x01\x12\x14\n\x07is_goto\x18\x08 \x01(\x08H\x03\x88\x01\x01\x12\x14\n\x07\x64ialect\x18\t \x01(\tH\x04\x88\x01\x01\x42\r\n\x0b_asm_stringB\x0c\n\n_is_simpleB\x0e\n\x0c_is_volatileB\n\n\x08_is_gotoB\n\n\x08_dialectJ\x04\x08\x01\x10\x02R\tstatementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.ms_asm_stmt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSASMSTMT']._serialized_start=70
  _globals['_MSASMSTMT']._serialized_end=385
# @@protoc_insertion_point(module_scope)
