# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/ms_guid_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/ms_guid_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61st/v1/ms_guid_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xde\x01\n\nMSGuidDecl\x12(\n\x05value\x18\x01 \x01(\x0b\x32\x19.ctk.ast.v1.ValueDeclInfo\x12\x12\n\x05\x64\x61ta1\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x12\n\x05\x64\x61ta2\x18\x03 \x01(\rH\x01\x88\x01\x01\x12\x12\n\x05\x64\x61ta3\x18\x04 \x01(\rH\x02\x88\x01\x01\x12\x12\n\x05\x64\x61ta4\x18\x05 \x01(\x0cH\x03\x88\x01\x01\x12.\n\x11value_as_constant\x18\x06 \x01(\x0b\x32\x13.ctk.ast.v1.APValueB\x08\n\x06_data1B\x08\n\x06_data2B\x08\n\x06_data3B\x08\n\x06_data4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.ms_guid_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGUIDDECL']._serialized_start=71
  _globals['_MSGUIDDECL']._serialized_end=293
# @@protoc_insertion_point(module_scope)
