from . import common_pb2 as _common_pb2  # noqa: E402, F401
from . import semantic_pb2 as _semantic_pb2  # noqa: E402, F401
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class UnsupportedReason(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    UNSUPPORTED_REASON_UNSPECIFIED: _ClassVar[UnsupportedReason]
    UNSUPPORTED_REASON_EXCLUDED_LANGUAGE: _ClassVar[UnsupportedReason]
    UNSUPPORTED_REASON_DEFERRED_CONTRACT: _ClassVar[UnsupportedReason]
UNSUPPORTED_REASON_UNSPECIFIED: UnsupportedReason
UNSUPPORTED_REASON_EXCLUDED_LANGUAGE: UnsupportedReason
UNSUPPORTED_REASON_DEFERRED_CONTRACT: UnsupportedReason

class AstNode(_message.Message):
    __slots__ = ("access_spec_decl", "binding_decl", "block_decl", "builtin_template_decl", "cxx_constructor_decl", "cxx_conversion_decl", "cxx_deduction_guide_decl", "cxx_destructor_decl", "cxx_method_decl", "cxx_record_decl", "class_template_decl", "class_template_partial_specialization_decl", "class_template_specialization_decl", "concept_decl", "constructor_using_shadow_decl", "decomposition_decl", "empty_decl", "enum_constant_decl", "enum_decl", "export_decl", "extern_c_context_decl", "field_decl", "file_scope_asm_decl", "friend_decl", "friend_template_decl", "function_decl", "function_template_decl", "implicit_concept_specialization_decl", "implicit_param_decl", "import_decl", "indirect_field_decl", "label_decl", "lifetime_extended_temporary_decl", "linkage_spec_decl", "ms_guid_decl", "ms_property_decl", "namespace_alias_decl", "namespace_decl", "non_type_template_parm_decl", "parm_var_decl", "pragma_comment_decl", "pragma_detect_mismatch_decl", "record_decl", "requires_expr_body_decl", "static_assert_decl", "template_param_object_decl", "template_template_parm_decl", "template_type_parm_decl", "top_level_stmt_decl", "translation_unit_decl", "type_alias_decl", "type_alias_template_decl", "typedef_decl", "unnamed_global_constant_decl", "unresolved_using_if_exists_decl", "unresolved_using_typename_decl", "unresolved_using_value_decl", "using_decl", "using_directive_decl", "using_enum_decl", "using_pack_decl", "using_shadow_decl", "var_decl", "var_template_decl", "var_template_partial_specialization_decl", "var_template_specialization_decl", "attributed_stmt", "break_stmt", "cxx_catch_stmt", "cxx_for_range_stmt", "cxx_try_stmt", "case_stmt", "compound_stmt", "continue_stmt", "coreturn_stmt", "coroutine_body_stmt", "decl_stmt", "default_stmt", "do_stmt", "for_stmt", "gcc_asm_stmt", "goto_stmt", "if_stmt", "indirect_goto_stmt", "label_stmt", "ms_asm_stmt", "ms_dependent_exists_stmt", "null_stmt", "return_stmt", "seh_except_stmt", "seh_finally_stmt", "seh_leave_stmt", "seh_try_stmt", "switch_stmt", "while_stmt", "addr_label_expr", "array_init_index_expr", "array_init_loop_expr", "array_subscript_expr", "array_type_trait_expr", "atomic_expr", "binary_conditional_operator", "binary_operator", "block_expr", "builtin_bit_cast_expr", "c_style_cast_expr", "cxx_addrspace_cast_expr", "cxx_bind_temporary_expr", "cxx_bool_literal_expr", "cxx_const_cast_expr", "cxx_construct_expr", "cxx_default_arg_expr", "cxx_default_init_expr", "cxx_delete_expr", "cxx_dependent_scope_member_expr", "cxx_dynamic_cast_expr", "cxx_fold_expr", "cxx_functional_cast_expr", "cxx_inherited_ctor_init_expr", "cxx_member_call_expr", "cxx_new_expr", "cxx_noexcept_expr", "cxx_null_ptr_literal_expr", "cxx_operator_call_expr", "cxx_paren_list_init_expr", "cxx_pseudo_destructor_expr", "cxx_reinterpret_cast_expr", "cxx_rewritten_binary_operator", "cxx_scalar_value_init_expr", "cxx_static_cast_expr", "cxx_std_initializer_list_expr", "cxx_temporary_object_expr", "cxx_this_expr", "cxx_throw_expr", "cxx_typeid_expr", "cxx_unresolved_construct_expr", "cxx_uuidof_expr", "call_expr", "character_literal", "choose_expr", "coawait_expr", "compound_assign_operator", "compound_literal_expr", "concept_specialization_expr", "conditional_operator", "constant_expr", "convert_vector_expr", "coyield_expr", "decl_ref_expr", "dependent_coawait_expr", "dependent_scope_decl_ref_expr", "designated_init_expr", "designated_init_update_expr", "embed_expr", "expr_with_cleanups", "expression_trait_expr", "ext_vector_element_expr", "fixed_point_literal", "floating_literal", "function_parm_pack_expr", "gnu_null_expr", "generic_selection_expr", "imaginary_literal", "implicit_cast_expr", "implicit_value_init_expr", "init_list_expr", "integer_literal", "lambda_expr", "ms_property_ref_expr", "ms_property_subscript_expr", "materialize_temporary_expr", "matrix_single_subscript_expr", "matrix_subscript_expr", "member_expr", "no_init_expr", "offset_of_expr", "opaque_value_expr", "pack_expansion_expr", "pack_indexing_expr", "paren_expr", "paren_list_expr", "predefined_expr", "pseudo_object_expr", "recovery_expr", "requires_expr", "shuffle_vector_expr", "size_of_pack_expr", "source_loc_expr", "stmt_expr", "string_literal", "subst_non_type_template_parm_expr", "subst_non_type_template_parm_pack_expr", "type_trait_expr", "unary_expr_or_type_trait_expr", "unary_operator", "unresolved_lookup_expr", "unresolved_member_expr", "user_defined_literal", "va_arg_expr", "adjusted_type", "atomic_type", "attributed_type", "auto_type", "btf_tag_attributed_type", "bit_int_type", "block_pointer_type", "builtin_type", "complex_type", "constant_array_type", "constant_matrix_type", "count_attributed_type", "decayed_type", "decltype_type", "deduced_template_specialization_type", "dependent_address_space_type", "dependent_bit_int_type", "dependent_decltype_type", "dependent_name_type", "dependent_sized_array_type", "dependent_sized_ext_vector_type", "dependent_sized_matrix_type", "dependent_type_of_expr_type", "dependent_vector_type", "enum_type", "ext_vector_type", "function_proto_type", "incomplete_array_type", "injected_class_name_type", "l_value_reference_type", "macro_qualified_type", "member_pointer_type", "pack_expansion_type", "pack_indexing_type", "paren_type", "pointer_type", "predefined_sugar_type", "r_value_reference_type", "record_type", "subst_builtin_template_pack_type", "subst_template_type_parm_pack_type", "subst_template_type_parm_type", "template_specialization_type", "template_type_parm_type", "type_of_expr_type", "type_of_type", "typedef_type", "unary_transform_type", "unresolved_using_type", "using_type", "variable_array_type", "vector_type")
    ACCESS_SPEC_DECL_FIELD_NUMBER: _ClassVar[int]
    BINDING_DECL_FIELD_NUMBER: _ClassVar[int]
    BLOCK_DECL_FIELD_NUMBER: _ClassVar[int]
    BUILTIN_TEMPLATE_DECL_FIELD_NUMBER: _ClassVar[int]
    CXX_CONSTRUCTOR_DECL_FIELD_NUMBER: _ClassVar[int]
    CXX_CONVERSION_DECL_FIELD_NUMBER: _ClassVar[int]
    CXX_DEDUCTION_GUIDE_DECL_FIELD_NUMBER: _ClassVar[int]
    CXX_DESTRUCTOR_DECL_FIELD_NUMBER: _ClassVar[int]
    CXX_METHOD_DECL_FIELD_NUMBER: _ClassVar[int]
    CXX_RECORD_DECL_FIELD_NUMBER: _ClassVar[int]
    CLASS_TEMPLATE_DECL_FIELD_NUMBER: _ClassVar[int]
    CLASS_TEMPLATE_PARTIAL_SPECIALIZATION_DECL_FIELD_NUMBER: _ClassVar[int]
    CLASS_TEMPLATE_SPECIALIZATION_DECL_FIELD_NUMBER: _ClassVar[int]
    CONCEPT_DECL_FIELD_NUMBER: _ClassVar[int]
    CONSTRUCTOR_USING_SHADOW_DECL_FIELD_NUMBER: _ClassVar[int]
    DECOMPOSITION_DECL_FIELD_NUMBER: _ClassVar[int]
    EMPTY_DECL_FIELD_NUMBER: _ClassVar[int]
    ENUM_CONSTANT_DECL_FIELD_NUMBER: _ClassVar[int]
    ENUM_DECL_FIELD_NUMBER: _ClassVar[int]
    EXPORT_DECL_FIELD_NUMBER: _ClassVar[int]
    EXTERN_C_CONTEXT_DECL_FIELD_NUMBER: _ClassVar[int]
    FIELD_DECL_FIELD_NUMBER: _ClassVar[int]
    FILE_SCOPE_ASM_DECL_FIELD_NUMBER: _ClassVar[int]
    FRIEND_DECL_FIELD_NUMBER: _ClassVar[int]
    FRIEND_TEMPLATE_DECL_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_DECL_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_TEMPLATE_DECL_FIELD_NUMBER: _ClassVar[int]
    IMPLICIT_CONCEPT_SPECIALIZATION_DECL_FIELD_NUMBER: _ClassVar[int]
    IMPLICIT_PARAM_DECL_FIELD_NUMBER: _ClassVar[int]
    IMPORT_DECL_FIELD_NUMBER: _ClassVar[int]
    INDIRECT_FIELD_DECL_FIELD_NUMBER: _ClassVar[int]
    LABEL_DECL_FIELD_NUMBER: _ClassVar[int]
    LIFETIME_EXTENDED_TEMPORARY_DECL_FIELD_NUMBER: _ClassVar[int]
    LINKAGE_SPEC_DECL_FIELD_NUMBER: _ClassVar[int]
    MS_GUID_DECL_FIELD_NUMBER: _ClassVar[int]
    MS_PROPERTY_DECL_FIELD_NUMBER: _ClassVar[int]
    NAMESPACE_ALIAS_DECL_FIELD_NUMBER: _ClassVar[int]
    NAMESPACE_DECL_FIELD_NUMBER: _ClassVar[int]
    NON_TYPE_TEMPLATE_PARM_DECL_FIELD_NUMBER: _ClassVar[int]
    PARM_VAR_DECL_FIELD_NUMBER: _ClassVar[int]
    PRAGMA_COMMENT_DECL_FIELD_NUMBER: _ClassVar[int]
    PRAGMA_DETECT_MISMATCH_DECL_FIELD_NUMBER: _ClassVar[int]
    RECORD_DECL_FIELD_NUMBER: _ClassVar[int]
    REQUIRES_EXPR_BODY_DECL_FIELD_NUMBER: _ClassVar[int]
    STATIC_ASSERT_DECL_FIELD_NUMBER: _ClassVar[int]
    TEMPLATE_PARAM_OBJECT_DECL_FIELD_NUMBER: _ClassVar[int]
    TEMPLATE_TEMPLATE_PARM_DECL_FIELD_NUMBER: _ClassVar[int]
    TEMPLATE_TYPE_PARM_DECL_FIELD_NUMBER: _ClassVar[int]
    TOP_LEVEL_STMT_DECL_FIELD_NUMBER: _ClassVar[int]
    TRANSLATION_UNIT_DECL_FIELD_NUMBER: _ClassVar[int]
    TYPE_ALIAS_DECL_FIELD_NUMBER: _ClassVar[int]
    TYPE_ALIAS_TEMPLATE_DECL_FIELD_NUMBER: _ClassVar[int]
    TYPEDEF_DECL_FIELD_NUMBER: _ClassVar[int]
    UNNAMED_GLOBAL_CONSTANT_DECL_FIELD_NUMBER: _ClassVar[int]
    UNRESOLVED_USING_IF_EXISTS_DECL_FIELD_NUMBER: _ClassVar[int]
    UNRESOLVED_USING_TYPENAME_DECL_FIELD_NUMBER: _ClassVar[int]
    UNRESOLVED_USING_VALUE_DECL_FIELD_NUMBER: _ClassVar[int]
    USING_DECL_FIELD_NUMBER: _ClassVar[int]
    USING_DIRECTIVE_DECL_FIELD_NUMBER: _ClassVar[int]
    USING_ENUM_DECL_FIELD_NUMBER: _ClassVar[int]
    USING_PACK_DECL_FIELD_NUMBER: _ClassVar[int]
    USING_SHADOW_DECL_FIELD_NUMBER: _ClassVar[int]
    VAR_DECL_FIELD_NUMBER: _ClassVar[int]
    VAR_TEMPLATE_DECL_FIELD_NUMBER: _ClassVar[int]
    VAR_TEMPLATE_PARTIAL_SPECIALIZATION_DECL_FIELD_NUMBER: _ClassVar[int]
    VAR_TEMPLATE_SPECIALIZATION_DECL_FIELD_NUMBER: _ClassVar[int]
    ATTRIBUTED_STMT_FIELD_NUMBER: _ClassVar[int]
    BREAK_STMT_FIELD_NUMBER: _ClassVar[int]
    CXX_CATCH_STMT_FIELD_NUMBER: _ClassVar[int]
    CXX_FOR_RANGE_STMT_FIELD_NUMBER: _ClassVar[int]
    CXX_TRY_STMT_FIELD_NUMBER: _ClassVar[int]
    CASE_STMT_FIELD_NUMBER: _ClassVar[int]
    COMPOUND_STMT_FIELD_NUMBER: _ClassVar[int]
    CONTINUE_STMT_FIELD_NUMBER: _ClassVar[int]
    CORETURN_STMT_FIELD_NUMBER: _ClassVar[int]
    COROUTINE_BODY_STMT_FIELD_NUMBER: _ClassVar[int]
    DECL_STMT_FIELD_NUMBER: _ClassVar[int]
    DEFAULT_STMT_FIELD_NUMBER: _ClassVar[int]
    DO_STMT_FIELD_NUMBER: _ClassVar[int]
    FOR_STMT_FIELD_NUMBER: _ClassVar[int]
    GCC_ASM_STMT_FIELD_NUMBER: _ClassVar[int]
    GOTO_STMT_FIELD_NUMBER: _ClassVar[int]
    IF_STMT_FIELD_NUMBER: _ClassVar[int]
    INDIRECT_GOTO_STMT_FIELD_NUMBER: _ClassVar[int]
    LABEL_STMT_FIELD_NUMBER: _ClassVar[int]
    MS_ASM_STMT_FIELD_NUMBER: _ClassVar[int]
    MS_DEPENDENT_EXISTS_STMT_FIELD_NUMBER: _ClassVar[int]
    NULL_STMT_FIELD_NUMBER: _ClassVar[int]
    RETURN_STMT_FIELD_NUMBER: _ClassVar[int]
    SEH_EXCEPT_STMT_FIELD_NUMBER: _ClassVar[int]
    SEH_FINALLY_STMT_FIELD_NUMBER: _ClassVar[int]
    SEH_LEAVE_STMT_FIELD_NUMBER: _ClassVar[int]
    SEH_TRY_STMT_FIELD_NUMBER: _ClassVar[int]
    SWITCH_STMT_FIELD_NUMBER: _ClassVar[int]
    WHILE_STMT_FIELD_NUMBER: _ClassVar[int]
    ADDR_LABEL_EXPR_FIELD_NUMBER: _ClassVar[int]
    ARRAY_INIT_INDEX_EXPR_FIELD_NUMBER: _ClassVar[int]
    ARRAY_INIT_LOOP_EXPR_FIELD_NUMBER: _ClassVar[int]
    ARRAY_SUBSCRIPT_EXPR_FIELD_NUMBER: _ClassVar[int]
    ARRAY_TYPE_TRAIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    ATOMIC_EXPR_FIELD_NUMBER: _ClassVar[int]
    BINARY_CONDITIONAL_OPERATOR_FIELD_NUMBER: _ClassVar[int]
    BINARY_OPERATOR_FIELD_NUMBER: _ClassVar[int]
    BLOCK_EXPR_FIELD_NUMBER: _ClassVar[int]
    BUILTIN_BIT_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    C_STYLE_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_ADDRSPACE_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_BIND_TEMPORARY_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_BOOL_LITERAL_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_CONST_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_CONSTRUCT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_DEFAULT_ARG_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_DEFAULT_INIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_DELETE_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_DEPENDENT_SCOPE_MEMBER_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_DYNAMIC_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_FOLD_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_FUNCTIONAL_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_INHERITED_CTOR_INIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_MEMBER_CALL_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_NEW_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_NOEXCEPT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_NULL_PTR_LITERAL_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_OPERATOR_CALL_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_PAREN_LIST_INIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_PSEUDO_DESTRUCTOR_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_REINTERPRET_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_REWRITTEN_BINARY_OPERATOR_FIELD_NUMBER: _ClassVar[int]
    CXX_SCALAR_VALUE_INIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_STATIC_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_STD_INITIALIZER_LIST_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_TEMPORARY_OBJECT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_THIS_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_THROW_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_TYPEID_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_UNRESOLVED_CONSTRUCT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CXX_UUIDOF_EXPR_FIELD_NUMBER: _ClassVar[int]
    CALL_EXPR_FIELD_NUMBER: _ClassVar[int]
    CHARACTER_LITERAL_FIELD_NUMBER: _ClassVar[int]
    CHOOSE_EXPR_FIELD_NUMBER: _ClassVar[int]
    COAWAIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    COMPOUND_ASSIGN_OPERATOR_FIELD_NUMBER: _ClassVar[int]
    COMPOUND_LITERAL_EXPR_FIELD_NUMBER: _ClassVar[int]
    CONCEPT_SPECIALIZATION_EXPR_FIELD_NUMBER: _ClassVar[int]
    CONDITIONAL_OPERATOR_FIELD_NUMBER: _ClassVar[int]
    CONSTANT_EXPR_FIELD_NUMBER: _ClassVar[int]
    CONVERT_VECTOR_EXPR_FIELD_NUMBER: _ClassVar[int]
    COYIELD_EXPR_FIELD_NUMBER: _ClassVar[int]
    DECL_REF_EXPR_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_COAWAIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_SCOPE_DECL_REF_EXPR_FIELD_NUMBER: _ClassVar[int]
    DESIGNATED_INIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    DESIGNATED_INIT_UPDATE_EXPR_FIELD_NUMBER: _ClassVar[int]
    EMBED_EXPR_FIELD_NUMBER: _ClassVar[int]
    EXPR_WITH_CLEANUPS_FIELD_NUMBER: _ClassVar[int]
    EXPRESSION_TRAIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    EXT_VECTOR_ELEMENT_EXPR_FIELD_NUMBER: _ClassVar[int]
    FIXED_POINT_LITERAL_FIELD_NUMBER: _ClassVar[int]
    FLOATING_LITERAL_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_PARM_PACK_EXPR_FIELD_NUMBER: _ClassVar[int]
    GNU_NULL_EXPR_FIELD_NUMBER: _ClassVar[int]
    GENERIC_SELECTION_EXPR_FIELD_NUMBER: _ClassVar[int]
    IMAGINARY_LITERAL_FIELD_NUMBER: _ClassVar[int]
    IMPLICIT_CAST_EXPR_FIELD_NUMBER: _ClassVar[int]
    IMPLICIT_VALUE_INIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    INIT_LIST_EXPR_FIELD_NUMBER: _ClassVar[int]
    INTEGER_LITERAL_FIELD_NUMBER: _ClassVar[int]
    LAMBDA_EXPR_FIELD_NUMBER: _ClassVar[int]
    MS_PROPERTY_REF_EXPR_FIELD_NUMBER: _ClassVar[int]
    MS_PROPERTY_SUBSCRIPT_EXPR_FIELD_NUMBER: _ClassVar[int]
    MATERIALIZE_TEMPORARY_EXPR_FIELD_NUMBER: _ClassVar[int]
    MATRIX_SINGLE_SUBSCRIPT_EXPR_FIELD_NUMBER: _ClassVar[int]
    MATRIX_SUBSCRIPT_EXPR_FIELD_NUMBER: _ClassVar[int]
    MEMBER_EXPR_FIELD_NUMBER: _ClassVar[int]
    NO_INIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    OFFSET_OF_EXPR_FIELD_NUMBER: _ClassVar[int]
    OPAQUE_VALUE_EXPR_FIELD_NUMBER: _ClassVar[int]
    PACK_EXPANSION_EXPR_FIELD_NUMBER: _ClassVar[int]
    PACK_INDEXING_EXPR_FIELD_NUMBER: _ClassVar[int]
    PAREN_EXPR_FIELD_NUMBER: _ClassVar[int]
    PAREN_LIST_EXPR_FIELD_NUMBER: _ClassVar[int]
    PREDEFINED_EXPR_FIELD_NUMBER: _ClassVar[int]
    PSEUDO_OBJECT_EXPR_FIELD_NUMBER: _ClassVar[int]
    RECOVERY_EXPR_FIELD_NUMBER: _ClassVar[int]
    REQUIRES_EXPR_FIELD_NUMBER: _ClassVar[int]
    SHUFFLE_VECTOR_EXPR_FIELD_NUMBER: _ClassVar[int]
    SIZE_OF_PACK_EXPR_FIELD_NUMBER: _ClassVar[int]
    SOURCE_LOC_EXPR_FIELD_NUMBER: _ClassVar[int]
    STMT_EXPR_FIELD_NUMBER: _ClassVar[int]
    STRING_LITERAL_FIELD_NUMBER: _ClassVar[int]
    SUBST_NON_TYPE_TEMPLATE_PARM_EXPR_FIELD_NUMBER: _ClassVar[int]
    SUBST_NON_TYPE_TEMPLATE_PARM_PACK_EXPR_FIELD_NUMBER: _ClassVar[int]
    TYPE_TRAIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    UNARY_EXPR_OR_TYPE_TRAIT_EXPR_FIELD_NUMBER: _ClassVar[int]
    UNARY_OPERATOR_FIELD_NUMBER: _ClassVar[int]
    UNRESOLVED_LOOKUP_EXPR_FIELD_NUMBER: _ClassVar[int]
    UNRESOLVED_MEMBER_EXPR_FIELD_NUMBER: _ClassVar[int]
    USER_DEFINED_LITERAL_FIELD_NUMBER: _ClassVar[int]
    VA_ARG_EXPR_FIELD_NUMBER: _ClassVar[int]
    ADJUSTED_TYPE_FIELD_NUMBER: _ClassVar[int]
    ATOMIC_TYPE_FIELD_NUMBER: _ClassVar[int]
    ATTRIBUTED_TYPE_FIELD_NUMBER: _ClassVar[int]
    AUTO_TYPE_FIELD_NUMBER: _ClassVar[int]
    BTF_TAG_ATTRIBUTED_TYPE_FIELD_NUMBER: _ClassVar[int]
    BIT_INT_TYPE_FIELD_NUMBER: _ClassVar[int]
    BLOCK_POINTER_TYPE_FIELD_NUMBER: _ClassVar[int]
    BUILTIN_TYPE_FIELD_NUMBER: _ClassVar[int]
    COMPLEX_TYPE_FIELD_NUMBER: _ClassVar[int]
    CONSTANT_ARRAY_TYPE_FIELD_NUMBER: _ClassVar[int]
    CONSTANT_MATRIX_TYPE_FIELD_NUMBER: _ClassVar[int]
    COUNT_ATTRIBUTED_TYPE_FIELD_NUMBER: _ClassVar[int]
    DECAYED_TYPE_FIELD_NUMBER: _ClassVar[int]
    DECLTYPE_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEDUCED_TEMPLATE_SPECIALIZATION_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_ADDRESS_SPACE_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_BIT_INT_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_DECLTYPE_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_NAME_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_SIZED_ARRAY_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_SIZED_EXT_VECTOR_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_SIZED_MATRIX_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_TYPE_OF_EXPR_TYPE_FIELD_NUMBER: _ClassVar[int]
    DEPENDENT_VECTOR_TYPE_FIELD_NUMBER: _ClassVar[int]
    ENUM_TYPE_FIELD_NUMBER: _ClassVar[int]
    EXT_VECTOR_TYPE_FIELD_NUMBER: _ClassVar[int]
    FUNCTION_PROTO_TYPE_FIELD_NUMBER: _ClassVar[int]
    INCOMPLETE_ARRAY_TYPE_FIELD_NUMBER: _ClassVar[int]
    INJECTED_CLASS_NAME_TYPE_FIELD_NUMBER: _ClassVar[int]
    L_VALUE_REFERENCE_TYPE_FIELD_NUMBER: _ClassVar[int]
    MACRO_QUALIFIED_TYPE_FIELD_NUMBER: _ClassVar[int]
    MEMBER_POINTER_TYPE_FIELD_NUMBER: _ClassVar[int]
    PACK_EXPANSION_TYPE_FIELD_NUMBER: _ClassVar[int]
    PACK_INDEXING_TYPE_FIELD_NUMBER: _ClassVar[int]
    PAREN_TYPE_FIELD_NUMBER: _ClassVar[int]
    POINTER_TYPE_FIELD_NUMBER: _ClassVar[int]
    PREDEFINED_SUGAR_TYPE_FIELD_NUMBER: _ClassVar[int]
    R_VALUE_REFERENCE_TYPE_FIELD_NUMBER: _ClassVar[int]
    RECORD_TYPE_FIELD_NUMBER: _ClassVar[int]
    SUBST_BUILTIN_TEMPLATE_PACK_TYPE_FIELD_NUMBER: _ClassVar[int]
    SUBST_TEMPLATE_TYPE_PARM_PACK_TYPE_FIELD_NUMBER: _ClassVar[int]
    SUBST_TEMPLATE_TYPE_PARM_TYPE_FIELD_NUMBER: _ClassVar[int]
    TEMPLATE_SPECIALIZATION_TYPE_FIELD_NUMBER: _ClassVar[int]
    TEMPLATE_TYPE_PARM_TYPE_FIELD_NUMBER: _ClassVar[int]
    TYPE_OF_EXPR_TYPE_FIELD_NUMBER: _ClassVar[int]
    TYPE_OF_TYPE_FIELD_NUMBER: _ClassVar[int]
    TYPEDEF_TYPE_FIELD_NUMBER: _ClassVar[int]
    UNARY_TRANSFORM_TYPE_FIELD_NUMBER: _ClassVar[int]
    UNRESOLVED_USING_TYPE_FIELD_NUMBER: _ClassVar[int]
    USING_TYPE_FIELD_NUMBER: _ClassVar[int]
    VARIABLE_ARRAY_TYPE_FIELD_NUMBER: _ClassVar[int]
    VECTOR_TYPE_FIELD_NUMBER: _ClassVar[int]
    access_spec_decl: _semantic_pb2.AccessSpecDecl
    binding_decl: _semantic_pb2.BindingDecl
    block_decl: _semantic_pb2.BlockDecl
    builtin_template_decl: _semantic_pb2.BuiltinTemplateDecl
    cxx_constructor_decl: _semantic_pb2.CXXConstructorDecl
    cxx_conversion_decl: _semantic_pb2.CXXConversionDecl
    cxx_deduction_guide_decl: _semantic_pb2.CXXDeductionGuideDecl
    cxx_destructor_decl: _semantic_pb2.CXXDestructorDecl
    cxx_method_decl: _semantic_pb2.CXXMethodDecl
    cxx_record_decl: _semantic_pb2.CXXRecordDecl
    class_template_decl: _semantic_pb2.ClassTemplateDecl
    class_template_partial_specialization_decl: _semantic_pb2.ClassTemplatePartialSpecializationDecl
    class_template_specialization_decl: _semantic_pb2.ClassTemplateSpecializationDecl
    concept_decl: _semantic_pb2.ConceptDecl
    constructor_using_shadow_decl: _semantic_pb2.ConstructorUsingShadowDecl
    decomposition_decl: _semantic_pb2.DecompositionDecl
    empty_decl: _semantic_pb2.EmptyDecl
    enum_constant_decl: _semantic_pb2.EnumConstantDecl
    enum_decl: _semantic_pb2.EnumDecl
    export_decl: _semantic_pb2.ExportDecl
    extern_c_context_decl: _semantic_pb2.ExternCContextDecl
    field_decl: _semantic_pb2.FieldDecl
    file_scope_asm_decl: _semantic_pb2.FileScopeAsmDecl
    friend_decl: _semantic_pb2.FriendDecl
    friend_template_decl: _semantic_pb2.FriendTemplateDecl
    function_decl: _semantic_pb2.FunctionDecl
    function_template_decl: _semantic_pb2.FunctionTemplateDecl
    implicit_concept_specialization_decl: _semantic_pb2.ImplicitConceptSpecializationDecl
    implicit_param_decl: _semantic_pb2.ImplicitParamDecl
    import_decl: _semantic_pb2.ImportDecl
    indirect_field_decl: _semantic_pb2.IndirectFieldDecl
    label_decl: _semantic_pb2.LabelDecl
    lifetime_extended_temporary_decl: _semantic_pb2.LifetimeExtendedTemporaryDecl
    linkage_spec_decl: _semantic_pb2.LinkageSpecDecl
    ms_guid_decl: _semantic_pb2.MSGuidDecl
    ms_property_decl: _semantic_pb2.MSPropertyDecl
    namespace_alias_decl: _semantic_pb2.NamespaceAliasDecl
    namespace_decl: _semantic_pb2.NamespaceDecl
    non_type_template_parm_decl: _semantic_pb2.NonTypeTemplateParmDecl
    parm_var_decl: _semantic_pb2.ParmVarDecl
    pragma_comment_decl: _semantic_pb2.PragmaCommentDecl
    pragma_detect_mismatch_decl: _semantic_pb2.PragmaDetectMismatchDecl
    record_decl: _semantic_pb2.RecordDecl
    requires_expr_body_decl: _semantic_pb2.RequiresExprBodyDecl
    static_assert_decl: _semantic_pb2.StaticAssertDecl
    template_param_object_decl: _semantic_pb2.TemplateParamObjectDecl
    template_template_parm_decl: _semantic_pb2.TemplateTemplateParmDecl
    template_type_parm_decl: _semantic_pb2.TemplateTypeParmDecl
    top_level_stmt_decl: _semantic_pb2.TopLevelStmtDecl
    translation_unit_decl: _semantic_pb2.TranslationUnitDecl
    type_alias_decl: _semantic_pb2.TypeAliasDecl
    type_alias_template_decl: _semantic_pb2.TypeAliasTemplateDecl
    typedef_decl: _semantic_pb2.TypedefDecl
    unnamed_global_constant_decl: _semantic_pb2.UnnamedGlobalConstantDecl
    unresolved_using_if_exists_decl: _semantic_pb2.UnresolvedUsingIfExistsDecl
    unresolved_using_typename_decl: _semantic_pb2.UnresolvedUsingTypenameDecl
    unresolved_using_value_decl: _semantic_pb2.UnresolvedUsingValueDecl
    using_decl: _semantic_pb2.UsingDecl
    using_directive_decl: _semantic_pb2.UsingDirectiveDecl
    using_enum_decl: _semantic_pb2.UsingEnumDecl
    using_pack_decl: _semantic_pb2.UsingPackDecl
    using_shadow_decl: _semantic_pb2.UsingShadowDecl
    var_decl: _semantic_pb2.VarDecl
    var_template_decl: _semantic_pb2.VarTemplateDecl
    var_template_partial_specialization_decl: _semantic_pb2.VarTemplatePartialSpecializationDecl
    var_template_specialization_decl: _semantic_pb2.VarTemplateSpecializationDecl
    attributed_stmt: _semantic_pb2.AttributedStmt
    break_stmt: _semantic_pb2.BreakStmt
    cxx_catch_stmt: _semantic_pb2.CXXCatchStmt
    cxx_for_range_stmt: _semantic_pb2.CXXForRangeStmt
    cxx_try_stmt: _semantic_pb2.CXXTryStmt
    case_stmt: _semantic_pb2.CaseStmt
    compound_stmt: _semantic_pb2.CompoundStmt
    continue_stmt: _semantic_pb2.ContinueStmt
    coreturn_stmt: _semantic_pb2.CoreturnStmt
    coroutine_body_stmt: _semantic_pb2.CoroutineBodyStmt
    decl_stmt: _semantic_pb2.DeclStmt
    default_stmt: _semantic_pb2.DefaultStmt
    do_stmt: _semantic_pb2.DoStmt
    for_stmt: _semantic_pb2.ForStmt
    gcc_asm_stmt: _semantic_pb2.GCCAsmStmt
    goto_stmt: _semantic_pb2.GotoStmt
    if_stmt: _semantic_pb2.IfStmt
    indirect_goto_stmt: _semantic_pb2.IndirectGotoStmt
    label_stmt: _semantic_pb2.LabelStmt
    ms_asm_stmt: _semantic_pb2.MSAsmStmt
    ms_dependent_exists_stmt: _semantic_pb2.MSDependentExistsStmt
    null_stmt: _semantic_pb2.NullStmt
    return_stmt: _semantic_pb2.ReturnStmt
    seh_except_stmt: _semantic_pb2.SEHExceptStmt
    seh_finally_stmt: _semantic_pb2.SEHFinallyStmt
    seh_leave_stmt: _semantic_pb2.SEHLeaveStmt
    seh_try_stmt: _semantic_pb2.SEHTryStmt
    switch_stmt: _semantic_pb2.SwitchStmt
    while_stmt: _semantic_pb2.WhileStmt
    addr_label_expr: _semantic_pb2.AddrLabelExpr
    array_init_index_expr: _semantic_pb2.ArrayInitIndexExpr
    array_init_loop_expr: _semantic_pb2.ArrayInitLoopExpr
    array_subscript_expr: _semantic_pb2.ArraySubscriptExpr
    array_type_trait_expr: _semantic_pb2.ArrayTypeTraitExpr
    atomic_expr: _semantic_pb2.AtomicExpr
    binary_conditional_operator: _semantic_pb2.BinaryConditionalOperator
    binary_operator: _semantic_pb2.BinaryOperator
    block_expr: _semantic_pb2.BlockExpr
    builtin_bit_cast_expr: _semantic_pb2.BuiltinBitCastExpr
    c_style_cast_expr: _semantic_pb2.CStyleCastExpr
    cxx_addrspace_cast_expr: _semantic_pb2.CXXAddrspaceCastExpr
    cxx_bind_temporary_expr: _semantic_pb2.CXXBindTemporaryExpr
    cxx_bool_literal_expr: _semantic_pb2.CXXBoolLiteralExpr
    cxx_const_cast_expr: _semantic_pb2.CXXConstCastExpr
    cxx_construct_expr: _semantic_pb2.CXXConstructExpr
    cxx_default_arg_expr: _semantic_pb2.CXXDefaultArgExpr
    cxx_default_init_expr: _semantic_pb2.CXXDefaultInitExpr
    cxx_delete_expr: _semantic_pb2.CXXDeleteExpr
    cxx_dependent_scope_member_expr: _semantic_pb2.CXXDependentScopeMemberExpr
    cxx_dynamic_cast_expr: _semantic_pb2.CXXDynamicCastExpr
    cxx_fold_expr: _semantic_pb2.CXXFoldExpr
    cxx_functional_cast_expr: _semantic_pb2.CXXFunctionalCastExpr
    cxx_inherited_ctor_init_expr: _semantic_pb2.CXXInheritedCtorInitExpr
    cxx_member_call_expr: _semantic_pb2.CXXMemberCallExpr
    cxx_new_expr: _semantic_pb2.CXXNewExpr
    cxx_noexcept_expr: _semantic_pb2.CXXNoexceptExpr
    cxx_null_ptr_literal_expr: _semantic_pb2.CXXNullPtrLiteralExpr
    cxx_operator_call_expr: _semantic_pb2.CXXOperatorCallExpr
    cxx_paren_list_init_expr: _semantic_pb2.CXXParenListInitExpr
    cxx_pseudo_destructor_expr: _semantic_pb2.CXXPseudoDestructorExpr
    cxx_reinterpret_cast_expr: _semantic_pb2.CXXReinterpretCastExpr
    cxx_rewritten_binary_operator: _semantic_pb2.CXXRewrittenBinaryOperator
    cxx_scalar_value_init_expr: _semantic_pb2.CXXScalarValueInitExpr
    cxx_static_cast_expr: _semantic_pb2.CXXStaticCastExpr
    cxx_std_initializer_list_expr: _semantic_pb2.CXXStdInitializerListExpr
    cxx_temporary_object_expr: _semantic_pb2.CXXTemporaryObjectExpr
    cxx_this_expr: _semantic_pb2.CXXThisExpr
    cxx_throw_expr: _semantic_pb2.CXXThrowExpr
    cxx_typeid_expr: _semantic_pb2.CXXTypeidExpr
    cxx_unresolved_construct_expr: _semantic_pb2.CXXUnresolvedConstructExpr
    cxx_uuidof_expr: _semantic_pb2.CXXUuidofExpr
    call_expr: _semantic_pb2.CallExpr
    character_literal: _semantic_pb2.CharacterLiteral
    choose_expr: _semantic_pb2.ChooseExpr
    coawait_expr: _semantic_pb2.CoawaitExpr
    compound_assign_operator: _semantic_pb2.CompoundAssignOperator
    compound_literal_expr: _semantic_pb2.CompoundLiteralExpr
    concept_specialization_expr: _semantic_pb2.ConceptSpecializationExpr
    conditional_operator: _semantic_pb2.ConditionalOperator
    constant_expr: _semantic_pb2.ConstantExpr
    convert_vector_expr: _semantic_pb2.ConvertVectorExpr
    coyield_expr: _semantic_pb2.CoyieldExpr
    decl_ref_expr: _semantic_pb2.DeclRefExpr
    dependent_coawait_expr: _semantic_pb2.DependentCoawaitExpr
    dependent_scope_decl_ref_expr: _semantic_pb2.DependentScopeDeclRefExpr
    designated_init_expr: _semantic_pb2.DesignatedInitExpr
    designated_init_update_expr: _semantic_pb2.DesignatedInitUpdateExpr
    embed_expr: _semantic_pb2.EmbedExpr
    expr_with_cleanups: _semantic_pb2.ExprWithCleanups
    expression_trait_expr: _semantic_pb2.ExpressionTraitExpr
    ext_vector_element_expr: _semantic_pb2.ExtVectorElementExpr
    fixed_point_literal: _semantic_pb2.FixedPointLiteral
    floating_literal: _semantic_pb2.FloatingLiteral
    function_parm_pack_expr: _semantic_pb2.FunctionParmPackExpr
    gnu_null_expr: _semantic_pb2.GNUNullExpr
    generic_selection_expr: _semantic_pb2.GenericSelectionExpr
    imaginary_literal: _semantic_pb2.ImaginaryLiteral
    implicit_cast_expr: _semantic_pb2.ImplicitCastExpr
    implicit_value_init_expr: _semantic_pb2.ImplicitValueInitExpr
    init_list_expr: _semantic_pb2.InitListExpr
    integer_literal: _semantic_pb2.IntegerLiteral
    lambda_expr: _semantic_pb2.LambdaExpr
    ms_property_ref_expr: _semantic_pb2.MSPropertyRefExpr
    ms_property_subscript_expr: _semantic_pb2.MSPropertySubscriptExpr
    materialize_temporary_expr: _semantic_pb2.MaterializeTemporaryExpr
    matrix_single_subscript_expr: _semantic_pb2.MatrixSingleSubscriptExpr
    matrix_subscript_expr: _semantic_pb2.MatrixSubscriptExpr
    member_expr: _semantic_pb2.MemberExpr
    no_init_expr: _semantic_pb2.NoInitExpr
    offset_of_expr: _semantic_pb2.OffsetOfExpr
    opaque_value_expr: _semantic_pb2.OpaqueValueExpr
    pack_expansion_expr: _semantic_pb2.PackExpansionExpr
    pack_indexing_expr: _semantic_pb2.PackIndexingExpr
    paren_expr: _semantic_pb2.ParenExpr
    paren_list_expr: _semantic_pb2.ParenListExpr
    predefined_expr: _semantic_pb2.PredefinedExpr
    pseudo_object_expr: _semantic_pb2.PseudoObjectExpr
    recovery_expr: _semantic_pb2.RecoveryExpr
    requires_expr: _semantic_pb2.RequiresExpr
    shuffle_vector_expr: _semantic_pb2.ShuffleVectorExpr
    size_of_pack_expr: _semantic_pb2.SizeOfPackExpr
    source_loc_expr: _semantic_pb2.SourceLocExpr
    stmt_expr: _semantic_pb2.StmtExpr
    string_literal: _semantic_pb2.StringLiteral
    subst_non_type_template_parm_expr: _semantic_pb2.SubstNonTypeTemplateParmExpr
    subst_non_type_template_parm_pack_expr: _semantic_pb2.SubstNonTypeTemplateParmPackExpr
    type_trait_expr: _semantic_pb2.TypeTraitExpr
    unary_expr_or_type_trait_expr: _semantic_pb2.UnaryExprOrTypeTraitExpr
    unary_operator: _semantic_pb2.UnaryOperator
    unresolved_lookup_expr: _semantic_pb2.UnresolvedLookupExpr
    unresolved_member_expr: _semantic_pb2.UnresolvedMemberExpr
    user_defined_literal: _semantic_pb2.UserDefinedLiteral
    va_arg_expr: _semantic_pb2.VAArgExpr
    adjusted_type: _semantic_pb2.AdjustedType
    atomic_type: _semantic_pb2.AtomicType
    attributed_type: _semantic_pb2.AttributedType
    auto_type: _semantic_pb2.AutoType
    btf_tag_attributed_type: _semantic_pb2.BTFTagAttributedType
    bit_int_type: _semantic_pb2.BitIntType
    block_pointer_type: _semantic_pb2.BlockPointerType
    builtin_type: _semantic_pb2.BuiltinType
    complex_type: _semantic_pb2.ComplexType
    constant_array_type: _semantic_pb2.ConstantArrayType
    constant_matrix_type: _semantic_pb2.ConstantMatrixType
    count_attributed_type: _semantic_pb2.CountAttributedType
    decayed_type: _semantic_pb2.DecayedType
    decltype_type: _semantic_pb2.DecltypeType
    deduced_template_specialization_type: _semantic_pb2.DeducedTemplateSpecializationType
    dependent_address_space_type: _semantic_pb2.DependentAddressSpaceType
    dependent_bit_int_type: _semantic_pb2.DependentBitIntType
    dependent_decltype_type: _semantic_pb2.DependentDecltypeType
    dependent_name_type: _semantic_pb2.DependentNameType
    dependent_sized_array_type: _semantic_pb2.DependentSizedArrayType
    dependent_sized_ext_vector_type: _semantic_pb2.DependentSizedExtVectorType
    dependent_sized_matrix_type: _semantic_pb2.DependentSizedMatrixType
    dependent_type_of_expr_type: _semantic_pb2.DependentTypeOfExprType
    dependent_vector_type: _semantic_pb2.DependentVectorType
    enum_type: _semantic_pb2.EnumType
    ext_vector_type: _semantic_pb2.ExtVectorType
    function_proto_type: _semantic_pb2.FunctionProtoType
    incomplete_array_type: _semantic_pb2.IncompleteArrayType
    injected_class_name_type: _semantic_pb2.InjectedClassNameType
    l_value_reference_type: _semantic_pb2.LValueReferenceType
    macro_qualified_type: _semantic_pb2.MacroQualifiedType
    member_pointer_type: _semantic_pb2.MemberPointerType
    pack_expansion_type: _semantic_pb2.PackExpansionType
    pack_indexing_type: _semantic_pb2.PackIndexingType
    paren_type: _semantic_pb2.ParenType
    pointer_type: _semantic_pb2.PointerType
    predefined_sugar_type: _semantic_pb2.PredefinedSugarType
    r_value_reference_type: _semantic_pb2.RValueReferenceType
    record_type: _semantic_pb2.RecordType
    subst_builtin_template_pack_type: _semantic_pb2.SubstBuiltinTemplatePackType
    subst_template_type_parm_pack_type: _semantic_pb2.SubstTemplateTypeParmPackType
    subst_template_type_parm_type: _semantic_pb2.SubstTemplateTypeParmType
    template_specialization_type: _semantic_pb2.TemplateSpecializationType
    template_type_parm_type: _semantic_pb2.TemplateTypeParmType
    type_of_expr_type: _semantic_pb2.TypeOfExprType
    type_of_type: _semantic_pb2.TypeOfType
    typedef_type: _semantic_pb2.TypedefType
    unary_transform_type: _semantic_pb2.UnaryTransformType
    unresolved_using_type: _semantic_pb2.UnresolvedUsingType
    using_type: _semantic_pb2.UsingType
    variable_array_type: _semantic_pb2.VariableArrayType
    vector_type: _semantic_pb2.VectorType
    def __init__(self, access_spec_decl: _Optional[_Union[_semantic_pb2.AccessSpecDecl, _Mapping]] = ..., binding_decl: _Optional[_Union[_semantic_pb2.BindingDecl, _Mapping]] = ..., block_decl: _Optional[_Union[_semantic_pb2.BlockDecl, _Mapping]] = ..., builtin_template_decl: _Optional[_Union[_semantic_pb2.BuiltinTemplateDecl, _Mapping]] = ..., cxx_constructor_decl: _Optional[_Union[_semantic_pb2.CXXConstructorDecl, _Mapping]] = ..., cxx_conversion_decl: _Optional[_Union[_semantic_pb2.CXXConversionDecl, _Mapping]] = ..., cxx_deduction_guide_decl: _Optional[_Union[_semantic_pb2.CXXDeductionGuideDecl, _Mapping]] = ..., cxx_destructor_decl: _Optional[_Union[_semantic_pb2.CXXDestructorDecl, _Mapping]] = ..., cxx_method_decl: _Optional[_Union[_semantic_pb2.CXXMethodDecl, _Mapping]] = ..., cxx_record_decl: _Optional[_Union[_semantic_pb2.CXXRecordDecl, _Mapping]] = ..., class_template_decl: _Optional[_Union[_semantic_pb2.ClassTemplateDecl, _Mapping]] = ..., class_template_partial_specialization_decl: _Optional[_Union[_semantic_pb2.ClassTemplatePartialSpecializationDecl, _Mapping]] = ..., class_template_specialization_decl: _Optional[_Union[_semantic_pb2.ClassTemplateSpecializationDecl, _Mapping]] = ..., concept_decl: _Optional[_Union[_semantic_pb2.ConceptDecl, _Mapping]] = ..., constructor_using_shadow_decl: _Optional[_Union[_semantic_pb2.ConstructorUsingShadowDecl, _Mapping]] = ..., decomposition_decl: _Optional[_Union[_semantic_pb2.DecompositionDecl, _Mapping]] = ..., empty_decl: _Optional[_Union[_semantic_pb2.EmptyDecl, _Mapping]] = ..., enum_constant_decl: _Optional[_Union[_semantic_pb2.EnumConstantDecl, _Mapping]] = ..., enum_decl: _Optional[_Union[_semantic_pb2.EnumDecl, _Mapping]] = ..., export_decl: _Optional[_Union[_semantic_pb2.ExportDecl, _Mapping]] = ..., extern_c_context_decl: _Optional[_Union[_semantic_pb2.ExternCContextDecl, _Mapping]] = ..., field_decl: _Optional[_Union[_semantic_pb2.FieldDecl, _Mapping]] = ..., file_scope_asm_decl: _Optional[_Union[_semantic_pb2.FileScopeAsmDecl, _Mapping]] = ..., friend_decl: _Optional[_Union[_semantic_pb2.FriendDecl, _Mapping]] = ..., friend_template_decl: _Optional[_Union[_semantic_pb2.FriendTemplateDecl, _Mapping]] = ..., function_decl: _Optional[_Union[_semantic_pb2.FunctionDecl, _Mapping]] = ..., function_template_decl: _Optional[_Union[_semantic_pb2.FunctionTemplateDecl, _Mapping]] = ..., implicit_concept_specialization_decl: _Optional[_Union[_semantic_pb2.ImplicitConceptSpecializationDecl, _Mapping]] = ..., implicit_param_decl: _Optional[_Union[_semantic_pb2.ImplicitParamDecl, _Mapping]] = ..., import_decl: _Optional[_Union[_semantic_pb2.ImportDecl, _Mapping]] = ..., indirect_field_decl: _Optional[_Union[_semantic_pb2.IndirectFieldDecl, _Mapping]] = ..., label_decl: _Optional[_Union[_semantic_pb2.LabelDecl, _Mapping]] = ..., lifetime_extended_temporary_decl: _Optional[_Union[_semantic_pb2.LifetimeExtendedTemporaryDecl, _Mapping]] = ..., linkage_spec_decl: _Optional[_Union[_semantic_pb2.LinkageSpecDecl, _Mapping]] = ..., ms_guid_decl: _Optional[_Union[_semantic_pb2.MSGuidDecl, _Mapping]] = ..., ms_property_decl: _Optional[_Union[_semantic_pb2.MSPropertyDecl, _Mapping]] = ..., namespace_alias_decl: _Optional[_Union[_semantic_pb2.NamespaceAliasDecl, _Mapping]] = ..., namespace_decl: _Optional[_Union[_semantic_pb2.NamespaceDecl, _Mapping]] = ..., non_type_template_parm_decl: _Optional[_Union[_semantic_pb2.NonTypeTemplateParmDecl, _Mapping]] = ..., parm_var_decl: _Optional[_Union[_semantic_pb2.ParmVarDecl, _Mapping]] = ..., pragma_comment_decl: _Optional[_Union[_semantic_pb2.PragmaCommentDecl, _Mapping]] = ..., pragma_detect_mismatch_decl: _Optional[_Union[_semantic_pb2.PragmaDetectMismatchDecl, _Mapping]] = ..., record_decl: _Optional[_Union[_semantic_pb2.RecordDecl, _Mapping]] = ..., requires_expr_body_decl: _Optional[_Union[_semantic_pb2.RequiresExprBodyDecl, _Mapping]] = ..., static_assert_decl: _Optional[_Union[_semantic_pb2.StaticAssertDecl, _Mapping]] = ..., template_param_object_decl: _Optional[_Union[_semantic_pb2.TemplateParamObjectDecl, _Mapping]] = ..., template_template_parm_decl: _Optional[_Union[_semantic_pb2.TemplateTemplateParmDecl, _Mapping]] = ..., template_type_parm_decl: _Optional[_Union[_semantic_pb2.TemplateTypeParmDecl, _Mapping]] = ..., top_level_stmt_decl: _Optional[_Union[_semantic_pb2.TopLevelStmtDecl, _Mapping]] = ..., translation_unit_decl: _Optional[_Union[_semantic_pb2.TranslationUnitDecl, _Mapping]] = ..., type_alias_decl: _Optional[_Union[_semantic_pb2.TypeAliasDecl, _Mapping]] = ..., type_alias_template_decl: _Optional[_Union[_semantic_pb2.TypeAliasTemplateDecl, _Mapping]] = ..., typedef_decl: _Optional[_Union[_semantic_pb2.TypedefDecl, _Mapping]] = ..., unnamed_global_constant_decl: _Optional[_Union[_semantic_pb2.UnnamedGlobalConstantDecl, _Mapping]] = ..., unresolved_using_if_exists_decl: _Optional[_Union[_semantic_pb2.UnresolvedUsingIfExistsDecl, _Mapping]] = ..., unresolved_using_typename_decl: _Optional[_Union[_semantic_pb2.UnresolvedUsingTypenameDecl, _Mapping]] = ..., unresolved_using_value_decl: _Optional[_Union[_semantic_pb2.UnresolvedUsingValueDecl, _Mapping]] = ..., using_decl: _Optional[_Union[_semantic_pb2.UsingDecl, _Mapping]] = ..., using_directive_decl: _Optional[_Union[_semantic_pb2.UsingDirectiveDecl, _Mapping]] = ..., using_enum_decl: _Optional[_Union[_semantic_pb2.UsingEnumDecl, _Mapping]] = ..., using_pack_decl: _Optional[_Union[_semantic_pb2.UsingPackDecl, _Mapping]] = ..., using_shadow_decl: _Optional[_Union[_semantic_pb2.UsingShadowDecl, _Mapping]] = ..., var_decl: _Optional[_Union[_semantic_pb2.VarDecl, _Mapping]] = ..., var_template_decl: _Optional[_Union[_semantic_pb2.VarTemplateDecl, _Mapping]] = ..., var_template_partial_specialization_decl: _Optional[_Union[_semantic_pb2.VarTemplatePartialSpecializationDecl, _Mapping]] = ..., var_template_specialization_decl: _Optional[_Union[_semantic_pb2.VarTemplateSpecializationDecl, _Mapping]] = ..., attributed_stmt: _Optional[_Union[_semantic_pb2.AttributedStmt, _Mapping]] = ..., break_stmt: _Optional[_Union[_semantic_pb2.BreakStmt, _Mapping]] = ..., cxx_catch_stmt: _Optional[_Union[_semantic_pb2.CXXCatchStmt, _Mapping]] = ..., cxx_for_range_stmt: _Optional[_Union[_semantic_pb2.CXXForRangeStmt, _Mapping]] = ..., cxx_try_stmt: _Optional[_Union[_semantic_pb2.CXXTryStmt, _Mapping]] = ..., case_stmt: _Optional[_Union[_semantic_pb2.CaseStmt, _Mapping]] = ..., compound_stmt: _Optional[_Union[_semantic_pb2.CompoundStmt, _Mapping]] = ..., continue_stmt: _Optional[_Union[_semantic_pb2.ContinueStmt, _Mapping]] = ..., coreturn_stmt: _Optional[_Union[_semantic_pb2.CoreturnStmt, _Mapping]] = ..., coroutine_body_stmt: _Optional[_Union[_semantic_pb2.CoroutineBodyStmt, _Mapping]] = ..., decl_stmt: _Optional[_Union[_semantic_pb2.DeclStmt, _Mapping]] = ..., default_stmt: _Optional[_Union[_semantic_pb2.DefaultStmt, _Mapping]] = ..., do_stmt: _Optional[_Union[_semantic_pb2.DoStmt, _Mapping]] = ..., for_stmt: _Optional[_Union[_semantic_pb2.ForStmt, _Mapping]] = ..., gcc_asm_stmt: _Optional[_Union[_semantic_pb2.GCCAsmStmt, _Mapping]] = ..., goto_stmt: _Optional[_Union[_semantic_pb2.GotoStmt, _Mapping]] = ..., if_stmt: _Optional[_Union[_semantic_pb2.IfStmt, _Mapping]] = ..., indirect_goto_stmt: _Optional[_Union[_semantic_pb2.IndirectGotoStmt, _Mapping]] = ..., label_stmt: _Optional[_Union[_semantic_pb2.LabelStmt, _Mapping]] = ..., ms_asm_stmt: _Optional[_Union[_semantic_pb2.MSAsmStmt, _Mapping]] = ..., ms_dependent_exists_stmt: _Optional[_Union[_semantic_pb2.MSDependentExistsStmt, _Mapping]] = ..., null_stmt: _Optional[_Union[_semantic_pb2.NullStmt, _Mapping]] = ..., return_stmt: _Optional[_Union[_semantic_pb2.ReturnStmt, _Mapping]] = ..., seh_except_stmt: _Optional[_Union[_semantic_pb2.SEHExceptStmt, _Mapping]] = ..., seh_finally_stmt: _Optional[_Union[_semantic_pb2.SEHFinallyStmt, _Mapping]] = ..., seh_leave_stmt: _Optional[_Union[_semantic_pb2.SEHLeaveStmt, _Mapping]] = ..., seh_try_stmt: _Optional[_Union[_semantic_pb2.SEHTryStmt, _Mapping]] = ..., switch_stmt: _Optional[_Union[_semantic_pb2.SwitchStmt, _Mapping]] = ..., while_stmt: _Optional[_Union[_semantic_pb2.WhileStmt, _Mapping]] = ..., addr_label_expr: _Optional[_Union[_semantic_pb2.AddrLabelExpr, _Mapping]] = ..., array_init_index_expr: _Optional[_Union[_semantic_pb2.ArrayInitIndexExpr, _Mapping]] = ..., array_init_loop_expr: _Optional[_Union[_semantic_pb2.ArrayInitLoopExpr, _Mapping]] = ..., array_subscript_expr: _Optional[_Union[_semantic_pb2.ArraySubscriptExpr, _Mapping]] = ..., array_type_trait_expr: _Optional[_Union[_semantic_pb2.ArrayTypeTraitExpr, _Mapping]] = ..., atomic_expr: _Optional[_Union[_semantic_pb2.AtomicExpr, _Mapping]] = ..., binary_conditional_operator: _Optional[_Union[_semantic_pb2.BinaryConditionalOperator, _Mapping]] = ..., binary_operator: _Optional[_Union[_semantic_pb2.BinaryOperator, _Mapping]] = ..., block_expr: _Optional[_Union[_semantic_pb2.BlockExpr, _Mapping]] = ..., builtin_bit_cast_expr: _Optional[_Union[_semantic_pb2.BuiltinBitCastExpr, _Mapping]] = ..., c_style_cast_expr: _Optional[_Union[_semantic_pb2.CStyleCastExpr, _Mapping]] = ..., cxx_addrspace_cast_expr: _Optional[_Union[_semantic_pb2.CXXAddrspaceCastExpr, _Mapping]] = ..., cxx_bind_temporary_expr: _Optional[_Union[_semantic_pb2.CXXBindTemporaryExpr, _Mapping]] = ..., cxx_bool_literal_expr: _Optional[_Union[_semantic_pb2.CXXBoolLiteralExpr, _Mapping]] = ..., cxx_const_cast_expr: _Optional[_Union[_semantic_pb2.CXXConstCastExpr, _Mapping]] = ..., cxx_construct_expr: _Optional[_Union[_semantic_pb2.CXXConstructExpr, _Mapping]] = ..., cxx_default_arg_expr: _Optional[_Union[_semantic_pb2.CXXDefaultArgExpr, _Mapping]] = ..., cxx_default_init_expr: _Optional[_Union[_semantic_pb2.CXXDefaultInitExpr, _Mapping]] = ..., cxx_delete_expr: _Optional[_Union[_semantic_pb2.CXXDeleteExpr, _Mapping]] = ..., cxx_dependent_scope_member_expr: _Optional[_Union[_semantic_pb2.CXXDependentScopeMemberExpr, _Mapping]] = ..., cxx_dynamic_cast_expr: _Optional[_Union[_semantic_pb2.CXXDynamicCastExpr, _Mapping]] = ..., cxx_fold_expr: _Optional[_Union[_semantic_pb2.CXXFoldExpr, _Mapping]] = ..., cxx_functional_cast_expr: _Optional[_Union[_semantic_pb2.CXXFunctionalCastExpr, _Mapping]] = ..., cxx_inherited_ctor_init_expr: _Optional[_Union[_semantic_pb2.CXXInheritedCtorInitExpr, _Mapping]] = ..., cxx_member_call_expr: _Optional[_Union[_semantic_pb2.CXXMemberCallExpr, _Mapping]] = ..., cxx_new_expr: _Optional[_Union[_semantic_pb2.CXXNewExpr, _Mapping]] = ..., cxx_noexcept_expr: _Optional[_Union[_semantic_pb2.CXXNoexceptExpr, _Mapping]] = ..., cxx_null_ptr_literal_expr: _Optional[_Union[_semantic_pb2.CXXNullPtrLiteralExpr, _Mapping]] = ..., cxx_operator_call_expr: _Optional[_Union[_semantic_pb2.CXXOperatorCallExpr, _Mapping]] = ..., cxx_paren_list_init_expr: _Optional[_Union[_semantic_pb2.CXXParenListInitExpr, _Mapping]] = ..., cxx_pseudo_destructor_expr: _Optional[_Union[_semantic_pb2.CXXPseudoDestructorExpr, _Mapping]] = ..., cxx_reinterpret_cast_expr: _Optional[_Union[_semantic_pb2.CXXReinterpretCastExpr, _Mapping]] = ..., cxx_rewritten_binary_operator: _Optional[_Union[_semantic_pb2.CXXRewrittenBinaryOperator, _Mapping]] = ..., cxx_scalar_value_init_expr: _Optional[_Union[_semantic_pb2.CXXScalarValueInitExpr, _Mapping]] = ..., cxx_static_cast_expr: _Optional[_Union[_semantic_pb2.CXXStaticCastExpr, _Mapping]] = ..., cxx_std_initializer_list_expr: _Optional[_Union[_semantic_pb2.CXXStdInitializerListExpr, _Mapping]] = ..., cxx_temporary_object_expr: _Optional[_Union[_semantic_pb2.CXXTemporaryObjectExpr, _Mapping]] = ..., cxx_this_expr: _Optional[_Union[_semantic_pb2.CXXThisExpr, _Mapping]] = ..., cxx_throw_expr: _Optional[_Union[_semantic_pb2.CXXThrowExpr, _Mapping]] = ..., cxx_typeid_expr: _Optional[_Union[_semantic_pb2.CXXTypeidExpr, _Mapping]] = ..., cxx_unresolved_construct_expr: _Optional[_Union[_semantic_pb2.CXXUnresolvedConstructExpr, _Mapping]] = ..., cxx_uuidof_expr: _Optional[_Union[_semantic_pb2.CXXUuidofExpr, _Mapping]] = ..., call_expr: _Optional[_Union[_semantic_pb2.CallExpr, _Mapping]] = ..., character_literal: _Optional[_Union[_semantic_pb2.CharacterLiteral, _Mapping]] = ..., choose_expr: _Optional[_Union[_semantic_pb2.ChooseExpr, _Mapping]] = ..., coawait_expr: _Optional[_Union[_semantic_pb2.CoawaitExpr, _Mapping]] = ..., compound_assign_operator: _Optional[_Union[_semantic_pb2.CompoundAssignOperator, _Mapping]] = ..., compound_literal_expr: _Optional[_Union[_semantic_pb2.CompoundLiteralExpr, _Mapping]] = ..., concept_specialization_expr: _Optional[_Union[_semantic_pb2.ConceptSpecializationExpr, _Mapping]] = ..., conditional_operator: _Optional[_Union[_semantic_pb2.ConditionalOperator, _Mapping]] = ..., constant_expr: _Optional[_Union[_semantic_pb2.ConstantExpr, _Mapping]] = ..., convert_vector_expr: _Optional[_Union[_semantic_pb2.ConvertVectorExpr, _Mapping]] = ..., coyield_expr: _Optional[_Union[_semantic_pb2.CoyieldExpr, _Mapping]] = ..., decl_ref_expr: _Optional[_Union[_semantic_pb2.DeclRefExpr, _Mapping]] = ..., dependent_coawait_expr: _Optional[_Union[_semantic_pb2.DependentCoawaitExpr, _Mapping]] = ..., dependent_scope_decl_ref_expr: _Optional[_Union[_semantic_pb2.DependentScopeDeclRefExpr, _Mapping]] = ..., designated_init_expr: _Optional[_Union[_semantic_pb2.DesignatedInitExpr, _Mapping]] = ..., designated_init_update_expr: _Optional[_Union[_semantic_pb2.DesignatedInitUpdateExpr, _Mapping]] = ..., embed_expr: _Optional[_Union[_semantic_pb2.EmbedExpr, _Mapping]] = ..., expr_with_cleanups: _Optional[_Union[_semantic_pb2.ExprWithCleanups, _Mapping]] = ..., expression_trait_expr: _Optional[_Union[_semantic_pb2.ExpressionTraitExpr, _Mapping]] = ..., ext_vector_element_expr: _Optional[_Union[_semantic_pb2.ExtVectorElementExpr, _Mapping]] = ..., fixed_point_literal: _Optional[_Union[_semantic_pb2.FixedPointLiteral, _Mapping]] = ..., floating_literal: _Optional[_Union[_semantic_pb2.FloatingLiteral, _Mapping]] = ..., function_parm_pack_expr: _Optional[_Union[_semantic_pb2.FunctionParmPackExpr, _Mapping]] = ..., gnu_null_expr: _Optional[_Union[_semantic_pb2.GNUNullExpr, _Mapping]] = ..., generic_selection_expr: _Optional[_Union[_semantic_pb2.GenericSelectionExpr, _Mapping]] = ..., imaginary_literal: _Optional[_Union[_semantic_pb2.ImaginaryLiteral, _Mapping]] = ..., implicit_cast_expr: _Optional[_Union[_semantic_pb2.ImplicitCastExpr, _Mapping]] = ..., implicit_value_init_expr: _Optional[_Union[_semantic_pb2.ImplicitValueInitExpr, _Mapping]] = ..., init_list_expr: _Optional[_Union[_semantic_pb2.InitListExpr, _Mapping]] = ..., integer_literal: _Optional[_Union[_semantic_pb2.IntegerLiteral, _Mapping]] = ..., lambda_expr: _Optional[_Union[_semantic_pb2.LambdaExpr, _Mapping]] = ..., ms_property_ref_expr: _Optional[_Union[_semantic_pb2.MSPropertyRefExpr, _Mapping]] = ..., ms_property_subscript_expr: _Optional[_Union[_semantic_pb2.MSPropertySubscriptExpr, _Mapping]] = ..., materialize_temporary_expr: _Optional[_Union[_semantic_pb2.MaterializeTemporaryExpr, _Mapping]] = ..., matrix_single_subscript_expr: _Optional[_Union[_semantic_pb2.MatrixSingleSubscriptExpr, _Mapping]] = ..., matrix_subscript_expr: _Optional[_Union[_semantic_pb2.MatrixSubscriptExpr, _Mapping]] = ..., member_expr: _Optional[_Union[_semantic_pb2.MemberExpr, _Mapping]] = ..., no_init_expr: _Optional[_Union[_semantic_pb2.NoInitExpr, _Mapping]] = ..., offset_of_expr: _Optional[_Union[_semantic_pb2.OffsetOfExpr, _Mapping]] = ..., opaque_value_expr: _Optional[_Union[_semantic_pb2.OpaqueValueExpr, _Mapping]] = ..., pack_expansion_expr: _Optional[_Union[_semantic_pb2.PackExpansionExpr, _Mapping]] = ..., pack_indexing_expr: _Optional[_Union[_semantic_pb2.PackIndexingExpr, _Mapping]] = ..., paren_expr: _Optional[_Union[_semantic_pb2.ParenExpr, _Mapping]] = ..., paren_list_expr: _Optional[_Union[_semantic_pb2.ParenListExpr, _Mapping]] = ..., predefined_expr: _Optional[_Union[_semantic_pb2.PredefinedExpr, _Mapping]] = ..., pseudo_object_expr: _Optional[_Union[_semantic_pb2.PseudoObjectExpr, _Mapping]] = ..., recovery_expr: _Optional[_Union[_semantic_pb2.RecoveryExpr, _Mapping]] = ..., requires_expr: _Optional[_Union[_semantic_pb2.RequiresExpr, _Mapping]] = ..., shuffle_vector_expr: _Optional[_Union[_semantic_pb2.ShuffleVectorExpr, _Mapping]] = ..., size_of_pack_expr: _Optional[_Union[_semantic_pb2.SizeOfPackExpr, _Mapping]] = ..., source_loc_expr: _Optional[_Union[_semantic_pb2.SourceLocExpr, _Mapping]] = ..., stmt_expr: _Optional[_Union[_semantic_pb2.StmtExpr, _Mapping]] = ..., string_literal: _Optional[_Union[_semantic_pb2.StringLiteral, _Mapping]] = ..., subst_non_type_template_parm_expr: _Optional[_Union[_semantic_pb2.SubstNonTypeTemplateParmExpr, _Mapping]] = ..., subst_non_type_template_parm_pack_expr: _Optional[_Union[_semantic_pb2.SubstNonTypeTemplateParmPackExpr, _Mapping]] = ..., type_trait_expr: _Optional[_Union[_semantic_pb2.TypeTraitExpr, _Mapping]] = ..., unary_expr_or_type_trait_expr: _Optional[_Union[_semantic_pb2.UnaryExprOrTypeTraitExpr, _Mapping]] = ..., unary_operator: _Optional[_Union[_semantic_pb2.UnaryOperator, _Mapping]] = ..., unresolved_lookup_expr: _Optional[_Union[_semantic_pb2.UnresolvedLookupExpr, _Mapping]] = ..., unresolved_member_expr: _Optional[_Union[_semantic_pb2.UnresolvedMemberExpr, _Mapping]] = ..., user_defined_literal: _Optional[_Union[_semantic_pb2.UserDefinedLiteral, _Mapping]] = ..., va_arg_expr: _Optional[_Union[_semantic_pb2.VAArgExpr, _Mapping]] = ..., adjusted_type: _Optional[_Union[_semantic_pb2.AdjustedType, _Mapping]] = ..., atomic_type: _Optional[_Union[_semantic_pb2.AtomicType, _Mapping]] = ..., attributed_type: _Optional[_Union[_semantic_pb2.AttributedType, _Mapping]] = ..., auto_type: _Optional[_Union[_semantic_pb2.AutoType, _Mapping]] = ..., btf_tag_attributed_type: _Optional[_Union[_semantic_pb2.BTFTagAttributedType, _Mapping]] = ..., bit_int_type: _Optional[_Union[_semantic_pb2.BitIntType, _Mapping]] = ..., block_pointer_type: _Optional[_Union[_semantic_pb2.BlockPointerType, _Mapping]] = ..., builtin_type: _Optional[_Union[_semantic_pb2.BuiltinType, _Mapping]] = ..., complex_type: _Optional[_Union[_semantic_pb2.ComplexType, _Mapping]] = ..., constant_array_type: _Optional[_Union[_semantic_pb2.ConstantArrayType, _Mapping]] = ..., constant_matrix_type: _Optional[_Union[_semantic_pb2.ConstantMatrixType, _Mapping]] = ..., count_attributed_type: _Optional[_Union[_semantic_pb2.CountAttributedType, _Mapping]] = ..., decayed_type: _Optional[_Union[_semantic_pb2.DecayedType, _Mapping]] = ..., decltype_type: _Optional[_Union[_semantic_pb2.DecltypeType, _Mapping]] = ..., deduced_template_specialization_type: _Optional[_Union[_semantic_pb2.DeducedTemplateSpecializationType, _Mapping]] = ..., dependent_address_space_type: _Optional[_Union[_semantic_pb2.DependentAddressSpaceType, _Mapping]] = ..., dependent_bit_int_type: _Optional[_Union[_semantic_pb2.DependentBitIntType, _Mapping]] = ..., dependent_decltype_type: _Optional[_Union[_semantic_pb2.DependentDecltypeType, _Mapping]] = ..., dependent_name_type: _Optional[_Union[_semantic_pb2.DependentNameType, _Mapping]] = ..., dependent_sized_array_type: _Optional[_Union[_semantic_pb2.DependentSizedArrayType, _Mapping]] = ..., dependent_sized_ext_vector_type: _Optional[_Union[_semantic_pb2.DependentSizedExtVectorType, _Mapping]] = ..., dependent_sized_matrix_type: _Optional[_Union[_semantic_pb2.DependentSizedMatrixType, _Mapping]] = ..., dependent_type_of_expr_type: _Optional[_Union[_semantic_pb2.DependentTypeOfExprType, _Mapping]] = ..., dependent_vector_type: _Optional[_Union[_semantic_pb2.DependentVectorType, _Mapping]] = ..., enum_type: _Optional[_Union[_semantic_pb2.EnumType, _Mapping]] = ..., ext_vector_type: _Optional[_Union[_semantic_pb2.ExtVectorType, _Mapping]] = ..., function_proto_type: _Optional[_Union[_semantic_pb2.FunctionProtoType, _Mapping]] = ..., incomplete_array_type: _Optional[_Union[_semantic_pb2.IncompleteArrayType, _Mapping]] = ..., injected_class_name_type: _Optional[_Union[_semantic_pb2.InjectedClassNameType, _Mapping]] = ..., l_value_reference_type: _Optional[_Union[_semantic_pb2.LValueReferenceType, _Mapping]] = ..., macro_qualified_type: _Optional[_Union[_semantic_pb2.MacroQualifiedType, _Mapping]] = ..., member_pointer_type: _Optional[_Union[_semantic_pb2.MemberPointerType, _Mapping]] = ..., pack_expansion_type: _Optional[_Union[_semantic_pb2.PackExpansionType, _Mapping]] = ..., pack_indexing_type: _Optional[_Union[_semantic_pb2.PackIndexingType, _Mapping]] = ..., paren_type: _Optional[_Union[_semantic_pb2.ParenType, _Mapping]] = ..., pointer_type: _Optional[_Union[_semantic_pb2.PointerType, _Mapping]] = ..., predefined_sugar_type: _Optional[_Union[_semantic_pb2.PredefinedSugarType, _Mapping]] = ..., r_value_reference_type: _Optional[_Union[_semantic_pb2.RValueReferenceType, _Mapping]] = ..., record_type: _Optional[_Union[_semantic_pb2.RecordType, _Mapping]] = ..., subst_builtin_template_pack_type: _Optional[_Union[_semantic_pb2.SubstBuiltinTemplatePackType, _Mapping]] = ..., subst_template_type_parm_pack_type: _Optional[_Union[_semantic_pb2.SubstTemplateTypeParmPackType, _Mapping]] = ..., subst_template_type_parm_type: _Optional[_Union[_semantic_pb2.SubstTemplateTypeParmType, _Mapping]] = ..., template_specialization_type: _Optional[_Union[_semantic_pb2.TemplateSpecializationType, _Mapping]] = ..., template_type_parm_type: _Optional[_Union[_semantic_pb2.TemplateTypeParmType, _Mapping]] = ..., type_of_expr_type: _Optional[_Union[_semantic_pb2.TypeOfExprType, _Mapping]] = ..., type_of_type: _Optional[_Union[_semantic_pb2.TypeOfType, _Mapping]] = ..., typedef_type: _Optional[_Union[_semantic_pb2.TypedefType, _Mapping]] = ..., unary_transform_type: _Optional[_Union[_semantic_pb2.UnaryTransformType, _Mapping]] = ..., unresolved_using_type: _Optional[_Union[_semantic_pb2.UnresolvedUsingType, _Mapping]] = ..., using_type: _Optional[_Union[_semantic_pb2.UsingType, _Mapping]] = ..., variable_array_type: _Optional[_Union[_semantic_pb2.VariableArrayType, _Mapping]] = ..., vector_type: _Optional[_Union[_semantic_pb2.VectorType, _Mapping]] = ...) -> None: ...

class UnsupportedValue(_message.Message):
    __slots__ = ("clang_kind", "clang_class", "reason", "detail")
    CLANG_KIND_FIELD_NUMBER: _ClassVar[int]
    CLANG_CLASS_FIELD_NUMBER: _ClassVar[int]
    REASON_FIELD_NUMBER: _ClassVar[int]
    DETAIL_FIELD_NUMBER: _ClassVar[int]
    clang_kind: str
    clang_class: str
    reason: UnsupportedReason
    detail: str
    def __init__(self, clang_kind: _Optional[str] = ..., clang_class: _Optional[str] = ..., reason: _Optional[_Union[UnsupportedReason, str]] = ..., detail: _Optional[str] = ...) -> None: ...

class SemanticResult(_message.Message):
    __slots__ = ("values", "availability", "unsupported_values", "is_complete")
    VALUES_FIELD_NUMBER: _ClassVar[int]
    AVAILABILITY_FIELD_NUMBER: _ClassVar[int]
    UNSUPPORTED_VALUES_FIELD_NUMBER: _ClassVar[int]
    IS_COMPLETE_FIELD_NUMBER: _ClassVar[int]
    values: _containers.RepeatedCompositeFieldContainer[AstNode]
    availability: _containers.RepeatedCompositeFieldContainer[_common_pb2.FieldAvailability]
    unsupported_values: _containers.RepeatedCompositeFieldContainer[UnsupportedValue]
    is_complete: bool
    def __init__(self, values: _Optional[_Iterable[_Union[AstNode, _Mapping]]] = ..., availability: _Optional[_Iterable[_Union[_common_pb2.FieldAvailability, _Mapping]]] = ..., unsupported_values: _Optional[_Iterable[_Union[UnsupportedValue, _Mapping]]] = ..., is_complete: _Optional[bool] = ...) -> None: ...
