# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/parm_var_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/parm_var_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61st/v1/parm_var_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xe9\x02\n\x0bParmVarDecl\x12)\n\x08variable\x18\x01 \x01(\x0b\x32\x17.ctk.ast.v1.VarDeclInfo\x12\x35\n\x10\x64\x65\x66\x61ult_argument\x18\x02 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValue\x12!\n\x14\x66unction_scope_index\x18\x03 \x01(\rH\x00\x88\x01\x01\x12!\n\x14\x66unction_scope_depth\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x1e\n\x11is_parameter_pack\x18\x05 \x01(\x08H\x02\x88\x01\x01\x12)\n\x1cis_explicit_object_parameter\x18\x06 \x01(\x08H\x03\x88\x01\x01\x42\x17\n\x15_function_scope_indexB\x17\n\x15_function_scope_depthB\x14\n\x12_is_parameter_packB\x1f\n\x1d_is_explicit_object_parameterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.parm_var_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARMVARDECL']._serialized_start=72
  _globals['_PARMVARDECL']._serialized_end=433
# @@protoc_insertion_point(module_scope)
