# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/string_literal.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/string_literal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61st/v1/string_literal.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\x97\x02\n\rStringLiteral\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.ctk.ast.v1.ExprInfo\x12\x12\n\x05value\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x1c\n\x0f\x63ode_unit_width\x18\x03 \x01(\rH\x01\x88\x01\x01\x12\x38\n\x0cliteral_kind\x18\x04 \x01(\x0e\x32\x1d.ctk.ast.v1.StringLiteralKindH\x02\x88\x01\x01\x12\x1c\n\x0f\x63ode_unit_count\x18\x05 \x01(\x04H\x03\x88\x01\x01\x42\x08\n\x06_valueB\x12\n\x10_code_unit_widthB\x0f\n\r_literal_kindB\x12\n\x10_code_unit_countJ\x04\x08\x06\x10\x07R\x0fsource_spellingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.string_literal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGLITERAL']._serialized_start=73
  _globals['_STRINGLITERAL']._serialized_end=352
# @@protoc_insertion_point(module_scope)
