# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/template_template_parm_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/template_template_parm_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ast/v1/template_template_parm_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\x95\x04\n\x18TemplateTemplateParmDecl\x12(\n\x05named\x18\x01 \x01(\x0b\x32\x19.ctk.ast.v1.NamedDeclInfo\x12>\n\x13template_parameters\x18\x02 \x01(\x0b\x32!.ctk.ast.v1.TemplateParameterList\x12\x12\n\x05\x64\x65pth\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x15\n\x08position\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x1e\n\x11is_parameter_pack\x18\x05 \x01(\x08H\x02\x88\x01\x01\x12\x36\n\x10\x64\x65\x66\x61ult_argument\x18\x06 \x01(\x0b\x32\x1c.ctk.ast.v1.TemplateArgument\x12+\n\x1e\x64\x65\x66\x61ult_argument_was_inherited\x18\x07 \x01(\x08H\x03\x88\x01\x01\x12\'\n\x1ais_expanded_parameter_pack\x18\x08 \x01(\x08H\x04\x88\x01\x01\x12G\n\x1c\x65xpanded_template_parameters\x18\t \x03(\x0b\x32!.ctk.ast.v1.TemplateParameterListB\x08\n\x06_depthB\x0b\n\t_positionB\x14\n\x12_is_parameter_packB!\n\x1f_default_argument_was_inheritedB\x1d\n\x1b_is_expanded_parameter_packb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.template_template_parm_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPLATETEMPLATEPARMDECL']._serialized_start=86
  _globals['_TEMPLATETEMPLATEPARMDECL']._serialized_end=619
# @@protoc_insertion_point(module_scope)
