# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/using_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/using_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61st/v1/using_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\xc4\x02\n\tUsingDecl\x12(\n\x05named\x18\x01 \x01(\x0b\x32\x19.ctk.ast.v1.NamedDeclInfo\x12\x32\n\tqualifier\x18\x02 \x01(\x0b\x32\x1f.ctk.ast.v1.NestedNameSpecifier\x12)\n\x04name\x18\x03 \x01(\x0b\x32\x1b.ctk.ast.v1.DeclarationName\x12.\n\x07shadows\x18\x04 \x03(\x0b\x32\x1d.ctk.ast.v1.DeclarationSymbol\x12\"\n\x15is_access_declaration\x18\x05 \x01(\x08H\x00\x88\x01\x01\x12\x19\n\x0chas_typename\x18\x06 \x01(\x08H\x01\x88\x01\x01\x42\x18\n\x16_is_access_declarationB\x0f\n\r_has_typenameJ\x04\x08\x07\x10\x08R\x0eusing_locationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.using_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USINGDECL']._serialized_start=69
  _globals['_USINGDECL']._serialized_end=393
# @@protoc_insertion_point(module_scope)
