# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ast/v1/var_decl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ast/v1/var_decl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import semantic_types_pb2 as ast_dot_v1_dot_semantic__types__pb2  # noqa: E402, F401


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61st/v1/var_decl.proto\x12\nctk.ast.v1\x1a\x1b\x61st/v1/semantic_types.proto\"\x8c\x03\n\x07VarDecl\x12)\n\x08variable\x18\x01 \x01(\x0b\x32\x17.ctk.ast.v1.VarDeclInfo\x12\x36\n\x08tls_kind\x18\x02 \x01(\x0e\x32\x1f.ctk.ast.v1.DeclVariableTLSKindH\x00\x88\x01\x01\x12N\n\x14initialization_style\x18\x03 \x01(\x0e\x32+.ctk.ast.v1.DeclVariableInitializationStyleH\x01\x88\x01\x01\x12\"\n\x15is_static_data_member\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\x45\n initializer_from_any_declaration\x18\x05 \x01(\x0b\x32\x1b.ctk.ast.v1.ExpressionValueB\x0b\n\t_tls_kindB\x17\n\x15_initialization_styleB\x18\n\x16_is_static_data_memberJ\x04\x08\x06\x10\x07R\x1dinitializer_owner_declarationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ast.v1.var_decl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VARDECL']._serialized_start=67
  _globals['_VARDECL']._serialized_end=463
# @@protoc_insertion_point(module_scope)
