# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: match/v1/match_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'match/v1/match_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import match_result_pb2 as match_dot_v1_dot_match__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmatch/v1/match_stream.proto\x12\x0c\x63tk.match.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bmatch/v1/match_result.proto\"~\n\x10MatchStreamEvent\x12(\n\x03row\x18\x01 \x01(\x0b\x32\x19.ctk.match.v1.MatchResultH\x00\x12\x37\n\tcompleted\x18\x02 \x01(\x0b\x32\".ctk.match.v1.MatchStreamCompletedH\x00\x42\x07\n\x05\x65vent\"\x86\x01\n\x14MatchStreamCompleted\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fresult_revision\x18\x02 \x01(\x04\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\trow_count\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'match.v1.match_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHSTREAMEVENT']._serialized_start=107
  _globals['_MATCHSTREAMEVENT']._serialized_end=233
  _globals['_MATCHSTREAMCOMPLETED']._serialized_start=236
  _globals['_MATCHSTREAMCOMPLETED']._serialized_end=370
# @@protoc_insertion_point(module_scope)
