# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import match_service_pb2 as match_dot_v1_dot_match__service__pb2
from . import match_stream_pb2 as match_dot_v1_dot_match__stream__pb2
from . import parse_request_pb2 as match_dot_v1_dot_parse__request__pb2
from . import parse_response_pb2 as match_dot_v1_dot_parse__response__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in match/v1/match_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.unary_unary(
                '/ctk.match.v1.MatchService/Parse',
                request_serializer=match_dot_v1_dot_parse__request__pb2.ParseRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_parse__response__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.Match = channel.unary_unary(
                '/ctk.match.v1.MatchService/Match',
                request_serializer=match_dot_v1_dot_match__service__pb2.MatchRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_match__service__pb2.MatchResponse.FromString,
                _registered_method=True)
        self.StreamMatch = channel.unary_stream(
                '/ctk.match.v1.MatchService/StreamMatch',
                request_serializer=match_dot_v1_dot_match__service__pb2.MatchRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_match__stream__pb2.MatchStreamEvent.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/ctk.match.v1.MatchService/CloseSession',
                request_serializer=match_dot_v1_dot_match__service__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_match__service__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/ctk.match.v1.MatchService/ListSessions',
                request_serializer=match_dot_v1_dot_match__service__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_match__service__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.AttachSession = channel.unary_unary(
                '/ctk.match.v1.MatchService/AttachSession',
                request_serializer=match_dot_v1_dot_match__service__pb2.AttachSessionRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_match__service__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.ServerStatus = channel.unary_unary(
                '/ctk.match.v1.MatchService/ServerStatus',
                request_serializer=match_dot_v1_dot_match__service__pb2.ServerStatusRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_match__service__pb2.ServerStatusResponse.FromString,
                _registered_method=True)
        self.PruneCaches = channel.unary_unary(
                '/ctk.match.v1.MatchService/PruneCaches',
                request_serializer=match_dot_v1_dot_match__service__pb2.PruneCachesRequest.SerializeToString,
                response_deserializer=match_dot_v1_dot_match__service__pb2.PruneCachesResponse.FromString,
                _registered_method=True)


class MatchServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Parse(self, request, context):
        """Acquire a pinned immutable tree without evaluating a matcher. The opaque
        tree cursor is caller-owned and is released by CloseSession or idle expiry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Match(self, request, context):
        """Parse and match a file, continue from prior bindings, or restart over a
        session's immutable AST. Each successful call atomically replaces the
        latest results and increments the session revision, even for zero rows,
        unless preserve_source requests an independent immutable result cursor.
        Failures and resource-limit errors commit no state. Cancellation/deadline
        prevents commit only when observed before the atomic commit; a lost
        response or later cancellation can leave the client unsure whether commit
        occurred. Operations on a session are serialized; stale revisions abort.
        Invalid requests or query expressions use INVALID_ARGUMENT; stale revisions
        use ABORTED; missing/expired sessions or selections use NOT_FOUND;
        unsupported continuation uses FAILED_PRECONDITION.
        RESOURCE_EXHAUSTED is all-or-error. CANCELLED and DEADLINE_EXCEEDED do not
        commit when observed before commit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMatch(self, request, context):
        """Stream each callback row as soon as it is serialized. Rows are provisional
        until exactly one completed event and terminal OK. Only successful native
        execution commits the cursor; failures/cancellation before commit preserve
        previous state. Completion has cursor metadata and a count, never all rows.
        Per-message wire limits apply to individual events, not their combined
        bytes. Native/snapshot/metadata retention and row-count limits still apply.
        Match remains available for legacy unary consumers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Close uses the same caller ownership as Match and is serialized with it.
        It affects only a session belonging to that caller. A malformed session ID
        is INVALID_ARGUMENT; a well-formed unavailable session is an idempotent OK.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Lists and attaches only cursors belonging to the transport's caller owner.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachSession(self, request, context):
        """Renews the idle lease and exposes a tree handle; it does not rerun matching.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStatus(self, request, context):
        """Resource accounting is process-wide; retained AST bytes are estimates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PruneCaches(self, request, context):
        """Releases reusable entries, never active cursor pins or disk leases.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=match_dot_v1_dot_parse__request__pb2.ParseRequest.FromString,
                    response_serializer=match_dot_v1_dot_parse__response__pb2.ParseResponse.SerializeToString,
            ),
            'Match': grpc.unary_unary_rpc_method_handler(
                    servicer.Match,
                    request_deserializer=match_dot_v1_dot_match__service__pb2.MatchRequest.FromString,
                    response_serializer=match_dot_v1_dot_match__service__pb2.MatchResponse.SerializeToString,
            ),
            'StreamMatch': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMatch,
                    request_deserializer=match_dot_v1_dot_match__service__pb2.MatchRequest.FromString,
                    response_serializer=match_dot_v1_dot_match__stream__pb2.MatchStreamEvent.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=match_dot_v1_dot_match__service__pb2.CloseSessionRequest.FromString,
                    response_serializer=match_dot_v1_dot_match__service__pb2.CloseSessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=match_dot_v1_dot_match__service__pb2.ListSessionsRequest.FromString,
                    response_serializer=match_dot_v1_dot_match__service__pb2.ListSessionsResponse.SerializeToString,
            ),
            'AttachSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachSession,
                    request_deserializer=match_dot_v1_dot_match__service__pb2.AttachSessionRequest.FromString,
                    response_serializer=match_dot_v1_dot_match__service__pb2.SessionInfo.SerializeToString,
            ),
            'ServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerStatus,
                    request_deserializer=match_dot_v1_dot_match__service__pb2.ServerStatusRequest.FromString,
                    response_serializer=match_dot_v1_dot_match__service__pb2.ServerStatusResponse.SerializeToString,
            ),
            'PruneCaches': grpc.unary_unary_rpc_method_handler(
                    servicer.PruneCaches,
                    request_deserializer=match_dot_v1_dot_match__service__pb2.PruneCachesRequest.FromString,
                    response_serializer=match_dot_v1_dot_match__service__pb2.PruneCachesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ctk.match.v1.MatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ctk.match.v1.MatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.match.v1.MatchService/Parse',
            match_dot_v1_dot_parse__request__pb2.ParseRequest.SerializeToString,
            match_dot_v1_dot_parse__response__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Match(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.match.v1.MatchService/Match',
            match_dot_v1_dot_match__service__pb2.MatchRequest.SerializeToString,
            match_dot_v1_dot_match__service__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ctk.match.v1.MatchService/StreamMatch',
            match_dot_v1_dot_match__service__pb2.MatchRequest.SerializeToString,
            match_dot_v1_dot_match__stream__pb2.MatchStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.match.v1.MatchService/CloseSession',
            match_dot_v1_dot_match__service__pb2.CloseSessionRequest.SerializeToString,
            match_dot_v1_dot_match__service__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.match.v1.MatchService/ListSessions',
            match_dot_v1_dot_match__service__pb2.ListSessionsRequest.SerializeToString,
            match_dot_v1_dot_match__service__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.match.v1.MatchService/AttachSession',
            match_dot_v1_dot_match__service__pb2.AttachSessionRequest.SerializeToString,
            match_dot_v1_dot_match__service__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.match.v1.MatchService/ServerStatus',
            match_dot_v1_dot_match__service__pb2.ServerStatusRequest.SerializeToString,
            match_dot_v1_dot_match__service__pb2.ServerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PruneCaches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.match.v1.MatchService/PruneCaches',
            match_dot_v1_dot_match__service__pb2.PruneCachesRequest.SerializeToString,
            match_dot_v1_dot_match__service__pb2.PruneCachesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
