# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: match/v1/saved_value.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'match/v1/saved_value.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amatch/v1/saved_value.proto\x12\x0c\x63tk.match.v1\"O\n\nSavedValue\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12)\n\x08\x65nvelope\x18\x02 \x01(\x0b\x32\x17.ctk.match.v1.SavedData\"\xa0\x02\n\tSavedData\x12\x32\n\nnull_value\x18\x01 \x01(\x0e\x32\x1c.ctk.match.v1.SavedData.NullH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x17\n\rinteger_value\x18\x03 \x01(\tH\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x05 \x01(\tH\x00\x12-\n\nlist_value\x18\x06 \x01(\x0b\x32\x17.ctk.match.v1.SavedListH\x00\x12\x31\n\x0crecord_value\x18\x07 \x01(\x0b\x32\x19.ctk.match.v1.SavedRecordH\x00\"\x16\n\x04Null\x12\x0e\n\nNULL_VALUE\x10\x00\x42\x07\n\x05value\"3\n\tSavedList\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.ctk.match.v1.SavedData\"\x8c\x01\n\x0bSavedRecord\x12\x35\n\x06\x66ields\x18\x01 \x03(\x0b\x32%.ctk.match.v1.SavedRecord.FieldsEntry\x1a\x46\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.ctk.match.v1.SavedData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'match.v1.saved_value_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVEDRECORD_FIELDSENTRY']._loaded_options = None
  _globals['_SAVEDRECORD_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_SAVEDVALUE']._serialized_start=44
  _globals['_SAVEDVALUE']._serialized_end=123
  _globals['_SAVEDDATA']._serialized_start=126
  _globals['_SAVEDDATA']._serialized_end=414
  _globals['_SAVEDDATA_NULL']._serialized_start=383
  _globals['_SAVEDDATA_NULL']._serialized_end=405
  _globals['_SAVEDLIST']._serialized_start=416
  _globals['_SAVEDLIST']._serialized_end=467
  _globals['_SAVEDRECORD']._serialized_start=470
  _globals['_SAVEDRECORD']._serialized_end=610
  _globals['_SAVEDRECORD_FIELDSENTRY']._serialized_start=540
  _globals['_SAVEDRECORD_FIELDSENTRY']._serialized_end=610
# @@protoc_insertion_point(module_scope)
