# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query/v1/errors.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'query/v1/errors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15query/v1/errors.proto\x12\x0c\x63tk.query.v1\"\x8b\x01\n\x0eLimitViolation\x12\x12\n\nlimit_name\x18\x01 \x01(\t\x12\x15\n\rcurrent_value\x18\x02 \x01(\x04\x12\x18\n\x10\x63onfigured_limit\x18\x03 \x01(\x04\x12\x1b\n\x13requested_increment\x18\x04 \x01(\x04\x12\x17\n\x0fprojected_value\x18\x05 \x01(\x04\"[\n\x08Rejected\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x30\n\nviolations\x18\x03 \x03(\x0b\x32\x1c.ctk.query.v1.LimitViolationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query.v1.errors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIMITVIOLATION']._serialized_start=40
  _globals['_LIMITVIOLATION']._serialized_end=179
  _globals['_REJECTED']._serialized_start=181
  _globals['_REJECTED']._serialized_end=272
# @@protoc_insertion_point(module_scope)
