# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query/v1/events.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'query/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import errors_pb2 as query_dot_v1_dot_errors__pb2  # noqa: E402, F401
from ...match.v1 import match_result_pb2 as match_dot_v1_dot_match__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15query/v1/events.proto\x12\x0c\x63tk.query.v1\x1a\x15query/v1/errors.proto\x1a\x1bmatch/v1/match_result.proto\"\"\n\x06Queued\x12\x18\n\x10pending_requests\x18\x01 \x01(\x04\"\t\n\x07Started\"Z\n\x08Progress\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0f\n\x07profile\x18\x02 \x01(\t\x12\x17\n\x0f\x63ompleted_files\x18\x03 \x01(\x04\x12\x16\n\x0e\x61\x63\x63\x65pted_files\x18\x04 \x01(\x04\";\n\x0fSemanticBinding\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"\xe9\x01\n\nMatchEvent\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0f\n\x07profile\x18\x02 \x01(\t\x12\x38\n\x08\x62indings\x18\x03 \x03(\x0b\x32&.ctk.query.v1.MatchEvent.BindingsEntry\x12\x32\n\x0fsemantic_result\x18\x04 \x01(\x0b\x32\x19.ctk.match.v1.MatchResult\x1aN\n\rBindingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.ctk.query.v1.SemanticBinding:\x02\x38\x01\"9\n\tCompleted\x12\x17\n\x0f\x63ompleted_files\x18\x01 \x01(\x04\x12\x13\n\x0bmatch_count\x18\x02 \x01(\x04\"\x19\n\x07\x43ontrol\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\"\xd6\x02\n\nQueryEvent\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12&\n\x06queued\x18\x02 \x01(\x0b\x32\x14.ctk.query.v1.QueuedH\x00\x12(\n\x07started\x18\x03 \x01(\x0b\x32\x15.ctk.query.v1.StartedH\x00\x12*\n\x08progress\x18\x04 \x01(\x0b\x32\x16.ctk.query.v1.ProgressH\x00\x12)\n\x05match\x18\x05 \x01(\x0b\x32\x18.ctk.query.v1.MatchEventH\x00\x12,\n\tcompleted\x18\x06 \x01(\x0b\x32\x17.ctk.query.v1.CompletedH\x00\x12*\n\x08rejected\x18\x07 \x01(\x0b\x32\x16.ctk.query.v1.RejectedH\x00\x12(\n\x07\x63ontrol\x18\x08 \x01(\x0b\x32\x15.ctk.query.v1.ControlH\x00\x42\x07\n\x05\x65ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHEVENT_BINDINGSENTRY']._loaded_options = None
  _globals['_MATCHEVENT_BINDINGSENTRY']._serialized_options = b'8\001'
  _globals['_QUEUED']._serialized_start=91
  _globals['_QUEUED']._serialized_end=125
  _globals['_STARTED']._serialized_start=127
  _globals['_STARTED']._serialized_end=136
  _globals['_PROGRESS']._serialized_start=138
  _globals['_PROGRESS']._serialized_end=228
  _globals['_SEMANTICBINDING']._serialized_start=230
  _globals['_SEMANTICBINDING']._serialized_end=289
  _globals['_MATCHEVENT']._serialized_start=292
  _globals['_MATCHEVENT']._serialized_end=525
  _globals['_MATCHEVENT_BINDINGSENTRY']._serialized_start=447
  _globals['_MATCHEVENT_BINDINGSENTRY']._serialized_end=525
  _globals['_COMPLETED']._serialized_start=527
  _globals['_COMPLETED']._serialized_end=584
  _globals['_CONTROL']._serialized_start=586
  _globals['_CONTROL']._serialized_end=611
  _globals['_QUERYEVENT']._serialized_start=614
  _globals['_QUERYEVENT']._serialized_end=956
# @@protoc_insertion_point(module_scope)
