# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import commands_pb2 as query_dot_v1_dot_commands__pb2  # noqa: E402, F401
from . import events_pb2 as query_dot_v1_dot_events__pb2  # noqa: E402, F401
from . import query_pb2 as query_dot_v1_dot_query__pb2  # noqa: E402, F401

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in query/v1/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub:
    """All calls share the application's retained analysis session. Completing a
    query does not release that session's retained file/profile resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/ctk.query.v1.QueryService/GetVersion',
                request_serializer=query_dot_v1_dot_query__pb2.VersionRequest.SerializeToString,
                response_deserializer=query_dot_v1_dot_query__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_stream(
                '/ctk.query.v1.QueryService/Query',
                request_serializer=query_dot_v1_dot_commands__pb2.QueryRequest.SerializeToString,
                response_deserializer=query_dot_v1_dot_events__pb2.QueryEvent.FromString,
                _registered_method=True)
        self.QuerySession = channel.stream_stream(
                '/ctk.query.v1.QueryService/QuerySession',
                request_serializer=query_dot_v1_dot_commands__pb2.QueryCommand.SerializeToString,
                response_deserializer=query_dot_v1_dot_events__pb2.QueryEvent.FromString,
                _registered_method=True)


class QueryServiceServicer:
    """All calls share the application's retained analysis session. Completing a
    query does not release that session's retained file/profile resources.
    """

    def GetVersion(self, request, context):
        """Identifies the running server binary without starting an analysis session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Fixed-file query. Foreground and background clients use the same RPC;
        background execution is client scheduling, not a separate server job API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySession(self, request_iterator, context):
        """Incremental query: StartQuery, AddFiles, Match, Pause and Resume.
        Native client half-close ends input; it does not cancel or resume work.
        A paused call must be resumed before half-close to finish, or cancelled
        through gRPC. The server drains accepted work and writes before finishing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=query_dot_v1_dot_query__pb2.VersionRequest.FromString,
                    response_serializer=query_dot_v1_dot_query__pb2.VersionResponse.SerializeToString,
            ),
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=query_dot_v1_dot_commands__pb2.QueryRequest.FromString,
                    response_serializer=query_dot_v1_dot_events__pb2.QueryEvent.SerializeToString,
            ),
            'QuerySession': grpc.stream_stream_rpc_method_handler(
                    servicer.QuerySession,
                    request_deserializer=query_dot_v1_dot_commands__pb2.QueryCommand.FromString,
                    response_serializer=query_dot_v1_dot_events__pb2.QueryEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ctk.query.v1.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ctk.query.v1.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService:
    """All calls share the application's retained analysis session. Completing a
    query does not release that session's retained file/profile resources.
    """

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctk.query.v1.QueryService/GetVersion',
            query_dot_v1_dot_query__pb2.VersionRequest.SerializeToString,
            query_dot_v1_dot_query__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ctk.query.v1.QueryService/Query',
            query_dot_v1_dot_commands__pb2.QueryRequest.SerializeToString,
            query_dot_v1_dot_events__pb2.QueryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ctk.query.v1.QueryService/QuerySession',
            query_dot_v1_dot_commands__pb2.QueryCommand.SerializeToString,
            query_dot_v1_dot_events__pb2.QueryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
