# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query/v1/query.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'query/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import commands_pb2 as query_dot_v1_dot_commands__pb2  # noqa: E402, F401
from . import errors_pb2 as query_dot_v1_dot_errors__pb2  # noqa: E402, F401
from . import events_pb2 as query_dot_v1_dot_events__pb2  # noqa: E402, F401

from .commands_pb2 import *  # noqa: E402, F403
from .errors_pb2 import *  # noqa: E402, F403
from .events_pb2 import *  # noqa: E402, F403

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14query/v1/query.proto\x12\x0c\x63tk.query.v1\x1a\x17query/v1/commands.proto\x1a\x15query/v1/errors.proto\x1a\x15query/v1/events.proto2\x99\x01\n\x0cQueryService\x12?\n\x05Query\x12\x1a.ctk.query.v1.QueryRequest\x1a\x18.ctk.query.v1.QueryEvent0\x01\x12H\n\x0cQuerySession\x12\x1a.ctk.query.v1.QueryCommand\x1a\x18.ctk.query.v1.QueryEvent(\x01\x30\x01P\x00P\x01P\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYSERVICE']._serialized_start=110
  _globals['_QUERYSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
