if(NOT TARGET ctk-server)
  return()
endif()

include(GNUInstallDirs)
set(_ctk_license_dir "${CMAKE_INSTALL_DATADIR}/licenses/clang-toolkit-server")
install(FILES "${CMAKE_SOURCE_DIR}/LICENSE"
        DESTINATION "${_ctk_license_dir}" COMPONENT ctk-server)
if(CTK_BUILD_SCRIPT)
  install(FILES "${CMAKE_SOURCE_DIR}/third_party/antlr/LICENSE.txt"
          DESTINATION "${_ctk_license_dir}" RENAME ANTLR-LICENSE.txt COMPONENT ctk-server)
endif()
if(NOT CTK_SYSTEM_SQLITE)
  install(FILES "${CMAKE_SOURCE_DIR}/third_party/sqlite/README.md"
          DESTINATION "${_ctk_license_dir}" RENAME SQLITE-NOTICE.md COMPONENT ctk-server)
endif()

# Set the root project's package metadata after dependencies include CPack.
set(CPACK_PACKAGE_NAME "clang-toolkit-server")
set(CPACK_PACKAGE_VENDOR "clang-toolkit contributors")
set(CPACK_PACKAGE_CONTACT "clang-toolkit contributors")
set(CPACK_PACKAGE_VERSION "${CMAKE_PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Clang toolkit native analysis server")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGING_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")
# Select only the server and its notices, excluding dependency headers/libraries.
set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_BINARY_DIR};${CMAKE_PROJECT_NAME};ctk-server;/")
set(CPACK_RPM_COMPONENT_INSTALL OFF)
set(CPACK_RPM_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_RPM_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}.rpm")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
if(CTK_BUILD_SCRIPT)
  string(APPEND CPACK_RPM_PACKAGE_LICENSE " AND BSD-3-Clause")
endif()
if(NOT CTK_SYSTEM_SQLITE)
  string(APPEND CPACK_RPM_PACKAGE_LICENSE " AND blessing")
endif()
set(CPACK_RPM_PACKAGE_URL "https://github.com/husams/clang-toolkit")
set(CPACK_RPM_PACKAGE_RELOCATABLE OFF)
set(CTK_PACKAGE_RELEASE "1" CACHE STRING "RPM package release number")
set(CPACK_RPM_PACKAGE_RELEASE "${CTK_PACKAGE_RELEASE}")
set(CPACK_RPM_PACKAGE_RELEASE_DIST ON)
if(CTK_WITH_CLANG)
  # The server also invokes clang and uses its builtin resource headers.
  set(CPACK_RPM_PACKAGE_REQUIRES "clang")
endif()
# rpmbuild adds shared-library runtime requirements automatically.
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CPACK_GENERATOR "RPM")
else()
  set(CPACK_GENERATOR "TGZ")
endif()
file(WRITE "${CMAKE_BINARY_DIR}/ctk-rpm-filename.txt" "${CPACK_RPM_FILE_NAME}\n")
include(CPack)
