#!/usr/bin/env python3
"""Assemble separately maintained recursive AST schemas for protoc.

Protobuf permits recursive message types in one file but rejects cyclic imports.
Each catalog node remains defined in its dedicated source schema; this build step
places their mutually recursive definitions in a single compilation unit and
emits public-import facades at the original import paths.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

from generate_nodes import ROOT


ASSEMBLED_FILE = "ast/v1/semantic.proto"
HELPER_FILE = "ast/v1/semantic_types.proto"
PREAMBLE = 'syntax = "proto3";\n\npackage ctk.ast.v1;\n\n'


def definitions(text: str) -> str:
    return re.sub(r'^(?:syntax|package|import)\b[^\n]*\n', "", text,
                  flags=re.MULTILINE).strip()


def assemble(output: Path) -> dict[str, str]:
    """Write compiler inputs, returning exact concrete-message source ownership."""
    catalog = json.loads((ROOT / "catalog.json").read_text())
    included = [entry for entry in catalog["classes"] if entry["status"] == "included"]
    sources: dict[str, str] = {}
    chunks = [PREAMBLE, '// Generated by api/assemble_ast.py; edit the dedicated source schemas.\n',
              'import "ast/v1/common.proto";\nimport "ast/v1/operators.proto";\n\n']
    helper_text = (ROOT / HELPER_FILE).read_text()
    chunks.append(f"// Source: {HELPER_FILE}\n{definitions(helper_text)}\n\n")
    for entry in included:
        relative = entry["protobuf_file"]
        text = (ROOT / relative).read_text()
        names = re.findall(r'^message\s+(\w+)\s*\{', text, flags=re.MULTILINE)
        if names != [entry["name"]]:
            raise ValueError(f"{relative} must define only its catalog node {entry['name']}")
        if relative in sources.values():
            raise ValueError(f"Catalog nodes share a dedicated source schema: {relative}")
        sources[entry["name"]] = relative
        chunks.append(f"// Source: {relative}\n{definitions(text)}\n\n")

    source_files = sorted(ROOT.rglob("*.proto"))
    facades = set(sources.values()) | {HELPER_FILE}
    for source in source_files:
        relative = source.relative_to(ROOT).as_posix()
        destination = output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        if relative == ASSEMBLED_FILE:
            content = "".join(chunks)
        elif relative in facades:
            content = (PREAMBLE + '// Generated compatibility import; definitions remain in the source schema.\n'
                       + f'import public "{ASSEMBLED_FILE}";\n')
        else:
            content = source.read_text()
        # Preserve timestamps for unchanged inputs so incremental builds stay small.
        if not destination.exists() or destination.read_text() != content:
            destination.write_text(content)
    (output / "ast_sources.json").write_text(json.dumps(sources, indent=2) + "\n")
    return sources


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    sources = assemble(args.output.resolve())
    print(f"Assembled {len(sources)} dedicated typed AST schemas")


if __name__ == "__main__":
    main()
