#!/usr/bin/env python3
"""Generate the typed node union from the explicit, stable wire-tag registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent


def field_name(name: str) -> str:
    value = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value).lower()


def render_wrappers() -> str:
    """Typed owned edges use the same stable discriminators as AstNode."""
    tags = json.loads((ROOT / "node_tags.json").read_text())["tags"]
    lines = []
    for family, wrapper in (("decl", "DeclarationValue"), ("expr", "ExpressionValue"),
                            ("stmt", "StatementValue"), ("type", "TypeValue")):
        lines.extend([f"message {wrapper} {{", "  reserved 2;", '  reserved "node";',
                      "  optional bool is_complete = 1;", "  oneof payload {"])
        if family == "stmt":
            lines.append("    ExpressionValue expression = 10;")
        for name, entry in sorted(tags.items(), key=lambda item: item[1]["tag"]):
            if entry["family"] == family:
                lines.append(f"    {name} {field_name(name)} = {entry['tag']};")
        lines.extend(["  }", "}", ""])
    return "\n".join(lines)


def render() -> str:
    catalog = json.loads((ROOT / "catalog.json").read_text())
    registry = json.loads((ROOT / "node_tags.json").read_text())
    expected = {entry["name"] for entry in catalog["classes"]
                if entry["status"] == "included"}
    tags = registry["tags"]
    if expected != set(tags):
        raise ValueError(f"Catalog/tag mismatch: {expected ^ set(tags)}")
    numbers = [entry["tag"] for entry in tags.values()]
    if len(numbers) != len(set(numbers)):
        raise ValueError("Duplicate payload tags")
    if any(n < 10 or 19000 <= n <= 19999 or n > 536870911 for n in numbers):
        raise ValueError("Invalid/reserved payload tag")
    if set(numbers) & set(registry["reserved_tags"]):
        raise ValueError("A payload tag was previously reserved")
    if set(tags) & set(registry["reserved_names"]):
        raise ValueError("A payload name was previously reserved")
    lines = [
        'syntax = "proto3";', '', 'package ctk.ast.v1;', '',
        'import "ast/v1/common.proto";', 'import "ast/v1/semantic.proto";', '',
        '// Generated by api/generate_nodes.py; numbers come from node_tags.json.',
        '// Never derive wire tags from Clang enum ordinals or rebuild the registry',
        '// with a new alphabetical order. Add new tags; reserve removed ones.',
        '// Self-contained semantic result; no opaque identifiers or lookup table.',
        'message AstNode {', '  reserved 1;', '  reserved "meta";',
    ]
    if registry["reserved_tags"]:
        lines.append('  reserved ' + ', '.join(map(str, registry["reserved_tags"])) + ';')
    if registry["reserved_names"]:
        names = ', '.join(json.dumps(field_name(n)) for n in registry["reserved_names"])
        lines.append(f'  reserved {names};')
    lines.append('  oneof payload {')
    for name, entry in sorted(tags.items(), key=lambda item: item[1]["tag"]):
        lines.append(f'    {name} {field_name(name)} = {entry["tag"]};')
    lines.extend(['  }', '}', '',
                  'enum UnsupportedReason {',
                  '  UNSUPPORTED_REASON_UNSPECIFIED = 0;',
                  '  UNSUPPORTED_REASON_EXCLUDED_LANGUAGE = 1;',
                  '  UNSUPPORTED_REASON_DEFERRED_CONTRACT = 2;',
                  '}', '',
                  '// Omitted semantic values are explained explicitly.',
                  'message UnsupportedValue {',
                  '  optional string clang_kind = 2;',
                  '  optional string clang_class = 3;',
                  '  optional UnsupportedReason reason = 4;',
                  '  optional string detail = 5;',
                  '}', '',
                  'message SemanticResult {',
                  '  repeated AstNode values = 1;',
                  '  repeated FieldAvailability availability = 2;',
                  '  repeated UnsupportedValue unsupported_values = 3;',
                  '  optional bool is_complete = 4;',
                  '}', ''])
    return '\n'.join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'ast/v1/node.proto'
    text = render()
    if args.check:
        if not target.exists() or target.read_text() != text:
            raise SystemExit('node.proto is stale; run api/generate_nodes.py')
        print('Node union matches the catalog and stable tag registry')
    else:
        target.write_text(text)


if __name__ == '__main__':
    main()
